<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="https://dacarras.github.io/">
<title>Regresión logística en R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&amp;family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&amp;display=swap" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99"><h2 id="toc-title">Contenido</h2>
   
  <ul>
<li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#introducci%C3%B3n" id="toc-introducción" class="nav-link" data-scroll-target="#introducci%C3%B3n">Introducción</a></li>
  <li><a href="#flujo-de-trabajo" id="toc-flujo-de-trabajo" class="nav-link" data-scroll-target="#flujo-de-trabajo">Flujo de trabajo</a></li>
  <li><a href="#abrir-datos" id="toc-abrir-datos" class="nav-link" data-scroll-target="#abrir-datos">1. Abrir datos</a></li>
  <li><a href="#preparar-datos" id="toc-preparar-datos" class="nav-link" data-scroll-target="#preparar-datos">2. Preparar datos</a></li>
  <li><a href="#ajustar-modelos" id="toc-ajustar-modelos" class="nav-link" data-scroll-target="#ajustar-modelos">3. Ajustar Modelos</a></li>
  <li>
<a href="#extraer-indicadores-de-ajuste" id="toc-extraer-indicadores-de-ajuste" class="nav-link" data-scroll-target="#extraer-indicadores-de-ajuste">4. Extraer indicadores de ajuste</a>
  <ul class="collapse">
<li><a href="#likelihood-ratio-test-lrt" id="toc-likelihood-ratio-test-lrt" class="nav-link" data-scroll-target="#likelihood-ratio-test-lrt">Likelihood Ratio Test (LRT)</a></li>
  <li><a href="#mcfadden-r2" id="toc-mcfadden-r2" class="nav-link" data-scroll-target="#mcfadden-r2">McFadden <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#horowitz-r2" id="toc-horowitz-r2" class="nav-link" data-scroll-target="#horowitz-r2">Horowitz <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#efrons-r2" id="toc-efrons-r2" class="nav-link" data-scroll-target="#efrons-r2">Efron’s <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#mckelvey-zavoina-pseudo-r2" id="toc-mckelvey-zavoina-pseudo-r2" class="nav-link" data-scroll-target="#mckelvey-zavoina-pseudo-r2">McKelvey &amp; Zavoina Pseudo <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#indicadores-de-ajuste" id="toc-indicadores-de-ajuste" class="nav-link" data-scroll-target="#indicadores-de-ajuste">Indicadores de ajuste</a></li>
  <li><a href="#qu%C3%A9-indicador-de-pseudo-r-emplear" id="toc-qué-indicador-de-pseudo-r-emplear" class="nav-link" data-scroll-target="#qu%C3%A9-indicador-de-pseudo-r-emplear">¿Qué indicador de Pseudo R emplear?</a></li>
  <li><a href="#calidad-de-la-clasificaci%C3%B3n" id="toc-calidad-de-la-clasificación" class="nav-link" data-scroll-target="#calidad-de-la-clasificaci%C3%B3n">Calidad de la clasificación</a></li>
  </ul>
</li>
  <li><a href="#tabla-de-resultados" id="toc-tabla-de-resultados" class="nav-link" data-scroll-target="#tabla-de-resultados">5. Tabla de resultados</a></li>
  <li><a href="#figura" id="toc-figura" class="nav-link" data-scroll-target="#figura">6. Figura</a></li>
  <li>
<a href="#descripcion-de-resultados" id="toc-descripcion-de-resultados" class="nav-link" data-scroll-target="#descripcion-de-resultados">7. Descripcion de resultados</a>
  <ul class="collapse">
<li><a href="#introducci%C3%B3n-1" id="toc-introducción-1" class="nav-link" data-scroll-target="#introducci%C3%B3n-1">Introducción</a></li>
  <li><a href="#m%C3%A9todo" id="toc-método" class="nav-link" data-scroll-target="#m%C3%A9todo">Método</a></li>
  <li><a href="#texto_resultados" id="toc-texto_resultados" class="nav-link" data-scroll-target="#texto_resultados">Resultados</a></li>
  </ul>
</li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  <li>
<a href="#anexos" id="toc-anexos" class="nav-link" data-scroll-target="#anexos">Anexos</a>
  <ul class="collapse">
<li><a href="#anexo-1-colinealidad" id="toc-anexo-1-colinealidad" class="nav-link" data-scroll-target="#anexo-1-colinealidad">Anexo 1: Colinealidad</a></li>
  <li><a href="#anexo-2-residuales" id="toc-anexo-2-residuales" class="nav-link" data-scroll-target="#anexo-2-residuales">Anexo 2: Residuales</a></li>
  <li><a href="#anexo-3-efectos-marginales-average-marginal-effects" id="toc-anexo-3-efectos-marginales-average-marginal-effects" class="nav-link" data-scroll-target="#anexo-3-efectos-marginales-average-marginal-effects">Anexo 3: Efectos marginales (Average Marginal Effects)</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Regresión logística en R</h1>
<p class="subtitle lead">Descripción de resultados empleando datos presentes en Osborne (2012)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>https://dacarras.github.io/ </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 29, 2024</p>
    </div>
  </div>
    
  </div>
  


</header><section id="resumen" class="level1"><h1>Resumen</h1>
<ul>
<li><p>La siguiente guía produce todos los pasos empleando R para abrir los datos, preparar los datos, ajustar modelos de regresión logística, y describir los resultados encontrados.</p></li>
<li><p>Este documento incluye diferentes secciones donde se ilustran los diferentes pasos que se pueden emplear para producir los resultados.</p></li>
<li><p>Para dirigirse específicamente a la descripción de <a href="#texto_resultados">resultados</a>, hacer <a href="#texto_resultados">click aqui</a>.</p></li>
</ul></section><section id="introducción" class="level1"><h1>Introducción</h1>
<p>El presente documento ilustra cómo describir resulados de regresión logística, empleando los datos y resultados presentes en Osborne (2012):</p>
<blockquote class="blockquote">
<p>Osborne, J. W. (2012). Logits and tigers and bears , oh my! A brief look at the simple math of logistic regression and how it can improve dissemination of results. Practical Assessment, Research and Evaluation, 17(June 2012), pp.&nbsp;1–10.</p>
</blockquote>
<p>En el articulo de Osborne (2012) se emplean datos del estudio NELS88 (https://nces.ed.gov/surveys/nels88/) de 1988, en el cual se siguen a estudiantes de 8vo grado (14 años aproximadamente), hasta el momento de graduación. Y con estos datos se distingue entre estudiantes que completan sus estudios y se graduan, en contraste a los estudiantes que interrumpen su trayectoria escolar. En resumen, la variable de respuesta, o variable dependiente, que se emplea se llama <code>dropout</code>. En esta se codifica como cero a los estudiantes que se graduan (i.e., completan la secundaria), y como uno a los estudiantes que interrumpen su trayectoria escolar.</p>
<p>Los datos que se emplean en la present guía, pueden ser obtenidos empleando el siguiente link:</p>
<ul>
<li><a href="https://www.dropbox.com/s/s1y0qkn8vuebqvr/NELS_data_pulll_2.SAV?dl=0">https://www.dropbox.com/s/s1y0qkn8vuebqvr/NELS_data_pulll_2.SAV?dl=0</a></li>
</ul>
<p>Para describir los resultados, se siguen cómo guía a las recomendaciones presentes en Huck (2012), O’Connell et al.&nbsp;(2019), y las observaciones Niu (2020), a la pra´ctica del reporte de resultados encontrados en la literatura de la investigación educacional.</p>
</section><section id="flujo-de-trabajo" class="level1"><h1>Flujo de trabajo</h1>
<ul>
<li><ol type="1">
<li>Abrir los datos</li>
</ol></li>
<li><ol start="2" type="1">
<li>Preparar los datos</li>
</ol></li>
<li><ol start="3" type="1">
<li>Ajustar Modelos</li>
</ol></li>
<li><ol start="4" type="1">
<li>Extraer indicadores de ajuste</li>
</ol></li>
<li><ol start="5" type="1">
<li>Crear tablas de resultados</li>
</ol></li>
<li><ol start="6" type="1">
<li>Crear figuras de resultados</li>
</ol></li>
<li><ol start="7" type="1">
<li>Descripcion de resultados</li>
</ol></li>
</ul>
<p>Para los puntos 1 a 6, vamos a re-utilizar código desarollado en la guia anterior.</p>
</section><section id="abrir-datos" class="level1"><h1>1. Abrir datos</h1>
<p>Primero procedemos a abrir los datos desde web link.</p>
<p><strong>Código 1.</strong> Abrir los datos desde URL</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># crear objeto con la ubicación de los datos</span></span>
<span id="cb1-2"><a href="#cb1-2"></a>file_url <span class="ot">&lt;-</span> <span class="st">'https://www.dropbox.com/s/s1y0qkn8vuebqvr/NELS_data_pulll_2.SAV?dl=1'</span> <span class="co">#</span></span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="co"># abrir los datos empleando haven</span></span>
<span id="cb1-5"><a href="#cb1-5"></a>data_nels <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_sav</span>(file_url)</span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="co"># inspeccionar datos cargados en R</span></span>
<span id="cb1-8"><a href="#cb1-8"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(data_nels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 16,610
Columns: 8
$ graduated &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ zses      &lt;dbl&gt; -0.61560884, -0.42631319, -1.02657966, -0.09753653, -0.19467…
$ ZACH      &lt;dbl&gt; 0.186200428, 0.625510312, 0.308392581, -0.062062995, -0.5614…
$ BYACH     &lt;dbl&gt; 0.26825101, 0.70913561, 0.39088116, 0.01909768, -0.48212874,…
$ dropout   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ byses     &lt;dbl&gt; -0.529, -0.377, -0.859, -0.113, -0.191, -0.238, -0.319, -0.2…
$ sex       &lt;dbl+lbl&gt; 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,…
$ poor      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, …</code></pre>
</div>
</div>
</section><section id="preparar-datos" class="level1"><h1>2. Preparar datos</h1>
<p>Vamos a crear un objeto llamado <code>data_model</code>, para alojar los datos en los que vamos a encontrar las observaciones que estaremos analizando. Este objeto es una copia de los datos originales, la cual solo contiene los datos que vamos a analizar. Este paso, es solo una buena práctica de analisis de datos la cual nos asegura que siempre podamos volver a nuestros datos originales, en caso de que quisieramos revocar un cambio realizado. Además, emplearemos nombres más cortos para las variables en uso (i.e., de unos 4 caracteres), y nombres homogeneos en miníscula, para que sea más facil escribir el código que emplearemos para producir los resultados.</p>
<p><strong>Código 2.</strong> preparar datos</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># crear datos analizables</span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3"></a>data_model <span class="ot">&lt;-</span> data_nels <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4"></a>              <span class="co"># crear variable de respuesta</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>              <span class="fu">mutate</span>(<span class="at">drop =</span> dropout) <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6"></a>              <span class="co"># covariables</span></span>
<span id="cb3-7"><a href="#cb3-7"></a>              <span class="fu">mutate</span>(<span class="at">zach =</span> ZACH) <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8"></a>              <span class="fu">mutate</span>(<span class="at">zses =</span> zses) <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9"></a>              <span class="fu">mutate</span>(<span class="at">int  =</span> zses<span class="sc">*</span>zach) <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10"></a>              <span class="co"># selección de variables en uso</span></span>
<span id="cb3-11"><a href="#cb3-11"></a>              dplyr<span class="sc">::</span><span class="fu">select</span>(drop, zach, zses, int)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Nota">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>En R los nombres de objetos <em>case sensitive</em>. Lo anterior quiere decir que a pesar de que dos palabras digan lo mismo, para R son objetos diferentes, si se diferencian por el uso de minúsculas y mayúsculas. De esta forma <code>variable</code>, <code>Variable</code>, y <code>VariaBle</code> son todos objetos diferentes. El presente código se apega al (“tidyerse style”)[https://style.tidyverse.org/index.html]. En este, todo lo de código se escribe con minúsculas, y se emplean <code>_</code> en caso de querer unir palabras.</p>
</div>
</div>
<p>Para los modelos que vamos a ajustar, solo vamos a emplear 4 variables:</p>
<ul>
<li>Variable dependiente o de respuesta.
<ul>
<li>
<code>drop</code>
<ul>
<li>0 = termina la secundaria</li>
<li>1 = no concluye la educación secundaría</li>
</ul>
</li>
</ul>
</li>
<li>Variables independientes
<ul>
<li>
<code>zach</code>
<ul>
<li>0 = media</li>
<li>1 = desviación estandar</li>
<li>Variable estandarizada</li>
<li>Mayor valor, mayor desempeño académico
<ul>
<li>Valor compuesto del desempeño escolar de 8vo grado</li>
</ul>
</li>
</ul>
</li>
<li>
<code>zses</code>
<ul>
<li>0 = media</li>
<li>1 = desviación estandar</li>
<li>Variable estandarizada</li>
<li>Mayor valor, mayor desempeño nivel socioeconómico de la familia de los estudiantes.
<ul>
<li>SES es una variable continua, generada como el compuesto de la educación de madre y padre, la ocupación de ambos padres, y el ingreso del hogar (ver NCES, 2018, p5)</li>
</ul>
</li>
</ul>
</li>
<li>
<code>int</code>
<ul>
<li>es el multiplo de <code>zses</code> y de <code>zach</code>, de tal forma que <code>zses*zach</code>.</li>
<li>Este término nos sirve para evaluar la posible interacción entre nivel socioeconómico, y desempeño académico de los estudiantes, en relación a la deserción escolar (<em>dropout</em>).</li>
</ul>
</li>
</ul>
</li>
</ul></section><section id="ajustar-modelos" class="level1"><h1>3. Ajustar Modelos</h1>
<p>En el siguiente código vamos a ajustar todos los modelos posibles, de forma incremental. Primero incluimos las covariables por si solas, y luego las variables juntas, y luego incluimos el término de interacción.</p>
<p><strong>Código 3.1</strong> ajustar modelos</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># ajustar modelos</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>m00 <span class="ot">&lt;-</span> <span class="fu">glm</span>(drop <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> data_model, <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb4-3"><a href="#cb4-3"></a>m01 <span class="ot">&lt;-</span> <span class="fu">glm</span>(drop <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> zach, <span class="at">data =</span> data_model, <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb4-4"><a href="#cb4-4"></a>m02 <span class="ot">&lt;-</span> <span class="fu">glm</span>(drop <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> zses, <span class="at">data =</span> data_model, <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb4-5"><a href="#cb4-5"></a>m03 <span class="ot">&lt;-</span> <span class="fu">glm</span>(drop <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> zach <span class="sc">+</span> zses, <span class="at">data =</span> data_model, <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb4-6"><a href="#cb4-6"></a>m04 <span class="ot">&lt;-</span> <span class="fu">glm</span>(drop <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> zach <span class="sc">+</span> zses <span class="sc">+</span> int, <span class="at">data =</span> data_model, <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb4-7"><a href="#cb4-7"></a></span>
<span id="cb4-8"><a href="#cb4-8"></a><span class="co"># sequencia completa de modelos</span></span>
<span id="cb4-9"><a href="#cb4-9"></a>texreg<span class="sc">::</span><span class="fu">screenreg</span>(</span>
<span id="cb4-10"><a href="#cb4-10"></a>  <span class="fu">list</span>(m00, m01, m02, m03, m04), </span>
<span id="cb4-11"><a href="#cb4-11"></a>  <span class="at">single.row =</span> <span class="cn">FALSE</span></span>
<span id="cb4-12"><a href="#cb4-12"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================================================
                Model 1       Model 2       Model 3       Model 4       Model 5     
------------------------------------------------------------------------------------
(Intercept)        -2.33 ***     -2.95 ***     -2.74 ***     -3.12 ***     -3.17 ***
                   (0.03)        (0.04)        (0.04)        (0.05)        (0.05)   
zach                             -1.36 ***                   -1.07 ***     -1.17 ***
                                 (0.04)                      (0.05)        (0.05)   
zses                                           -1.04 ***     -0.70 ***     -0.86 ***
                                               (0.03)        (0.04)        (0.05)   
int                                                                        -0.21 ***
                                                                           (0.05)   
------------------------------------------------------------------------------------
AIC              9969.24       8479.86       8743.91       8068.99       8053.52    
BIC              9976.96       8495.30       8759.35       8092.14       8084.39    
Log Likelihood  -4983.62      -4237.93      -4369.96      -4031.49      -4022.76    
Deviance         9967.24       8475.86       8739.91       8062.99       8045.52    
Num. obs.       16610         16610         16610         16610         16610       
====================================================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p>En el paso anterior, ajustamos todos los modelos posibles. Esto nos da una vista panóramica de la relación de cada una de las variables con respecto a la variable de respuesta. El paso anterior, nos puede dar un diagnóstico rápido si las variables presentan varianza compartida, y si pudiera existir problemas de colinealidad (ver Anexos: <em>Colinealidad</em>).</p>
<p>Ahora, solo ajustaremos los modelos que vamos a emplear para la descripción de resultados.</p>
<p><strong>Código 3.2</strong> ajustar modelos seleccionados.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># sequencia seleccionada de modelos</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>texreg<span class="sc">::</span><span class="fu">screenreg</span>(</span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="fu">list</span>(m00, m03, m04), </span>
<span id="cb6-4"><a href="#cb6-4"></a>  <span class="at">single.row =</span> <span class="cn">FALSE</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
========================================================
                Model 1       Model 2       Model 3     
--------------------------------------------------------
(Intercept)        -2.33 ***     -3.12 ***     -3.17 ***
                   (0.03)        (0.05)        (0.05)   
zach                             -1.07 ***     -1.17 ***
                                 (0.05)        (0.05)   
zses                             -0.70 ***     -0.86 ***
                                 (0.04)        (0.05)   
int                                            -0.21 ***
                                               (0.05)   
--------------------------------------------------------
AIC              9969.24       8068.99       8053.52    
BIC              9976.96       8092.14       8084.39    
Log Likelihood  -4983.62      -4031.49      -4022.76    
Deviance         9967.24       8062.99       8045.52    
Num. obs.       16610         16610         16610       
========================================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
</div>
<p>Para obtener los odds ratio, vamos a emplear dos librerias. Una de ellas es la librería <a href="https://blorr.rsquaredacademy.com/articles/introduction"><code>blorr</code></a>, y la otra es la librería <a href="https://broom.tidymodels.org/"><code>broom</code></a>. <code>blorr</code> es una librería para ajustar modelos de regresión logística, que posee diferentes funciones para obtener diferentes aspectos de interés, como relaciones bivariadas, odds ratio, indicadores de ajuste, entre otros aspectos. <code>broom</code>, por su parte, es una librería general para extraer coeficientes e indicadores de ajuste, en formato tabla desde varios modelos en R.</p>
<p>Con los códigos siguientes, vamos a obtener los odds ratio implicados por el modelo ajustado. Recordemos que los odds ratio son solo los coeficientes exponenienciados. Es decir:</p>
<p><span class="math inline">\(\text{odds ratio }= exp(\hat{\beta}_{1-n})\)</span></p>
<p><strong>Código 3.3</strong> odds ratio.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># obtener odds ratio con blorr</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>blorr<span class="sc">::</span><span class="fu">blr_regress</span>(m04, <span class="at">odd_conf_limit =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             Model Overview                               
-------------------------------------------------------------------------
Data Set    Resp Var     Obs.    Df. Model    Df. Residual    Convergence 
-------------------------------------------------------------------------
  data        drop      16610      16609         16606           TRUE     
-------------------------------------------------------------------------

                    Response Summary                     
--------------------------------------------------------
Outcome        Frequency        Outcome        Frequency 
--------------------------------------------------------
   0             15133             1             1477    
--------------------------------------------------------

                   Maximum Likelihood Estimates                    
------------------------------------------------------------------
 Parameter     DF    Estimate    Std. Error    z value     Pr(&gt;|z|) 
------------------------------------------------------------------
(Intercept)    1     -3.1743        0.0540    -58.8165      0.0000 
   zach        1     -1.1744        0.0548    -21.4362      0.0000 
   zses        1     -0.8570        0.0540    -15.8635      0.0000 
    int        1     -0.2093        0.0514     -4.0744      0.0000 
------------------------------------------------------------------

                   Odds Ratio Estimates                    
----------------------------------------------------------
 Effects          Estimate           95% Wald Conf. Limit 
----------------------------------------------------------
   zach            0.3090           0.2770          0.3434 
   zses            0.4244           0.3814          0.4713 
   int             0.8111           0.7326          0.8960 
----------------------------------------------------------

 Association of Predicted Probabilities and Observed Responses  
---------------------------------------------------------------
% Concordant          0.8200          Somers' D        0.6400   
% Discordant          0.1800          Gamma            0.6400   
% Tied                0.0000          Tau-a            0.1037   
Pairs                22351441         c                0.8200   
---------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co"># obtener odds ratio con broom</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(m04, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term        estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   0.0418    0.0540    -58.8  0           0.0375    0.0464
2 zach          0.309     0.0548    -21.4  6.14e-102   0.277     0.343 
3 zses          0.424     0.0540    -15.9  1.13e- 56   0.381     0.471 
4 int           0.811     0.0514     -4.07 4.61e-  5   0.733     0.896 </code></pre>
</div>
</div>
</section><section id="extraer-indicadores-de-ajuste" class="level1"><h1>4. Extraer indicadores de ajuste</h1>
<p>Los modelos de regresión logística, poseen diferentes indicadores de ajuste. Entre estos indicadores tenemos:</p>
<ul>
<li>La prueba global de Likelihood ratio
<ul>
<li>Esta prueba global compara si la reducción de devianza se encuentra por sobre el azar.</li>
<li>Es muy similar a la prueba de ANOVA de regresion lineal, en que se compara el modelo nulo, en contraste al modelo seleccionado con predictores.</li>
</ul>
</li>
<li>pseudo R^2 o R^2 generalizados
<ul>
<li>La regresión logística no posee un único indicador de varianza explicada, tipo R^2</li>
<li>En cambio, existen una colección de estos indicadores tales como:
<ul>
<li>McFadden’s R^2, Cox-Snell R^2, Efron R^2, McKelvey &amp; Zavoinas R2, entre otros.</li>
</ul>
</li>
</ul>
</li>
<li>Indicadores de calidad de la clasificación del modelo
<ul>
<li>En estos indicadores comúnmente se cuenta la cantidad de <span class="math inline">\(Pr(y=1)\)</span> de <span class="math inline">\(Pr(y=0)\)</span> sobre la cantidad de observaciones. Con estos se producen indicadores de sensibilidad, especificidad y precisión de clasificación.</li>
<li>Una forma de obtener estos indicadores, es mediante una tabla de “confusión” (i.e., <em>confusion matrix</em>). Esta es una tabla de contigencia que cruza los valores observados de <span class="math inline">\(y\)</span>, en contraste a los valores esperados de y (<span class="math inline">\(\hat{y}\)</span>).</li>
</ul>
</li>
</ul>
<p>A continuación revisaremos como se construyen los indicadores de likelihood (LRT), McFadden’s R^2, y Efron R^2, y las tablas de clasificación.</p>
<section id="likelihood-ratio-test-lrt" class="level2"><h2 class="anchored" data-anchor-id="likelihood-ratio-test-lrt">Likelihood Ratio Test (LRT)</h2>
<p>La formula de Likelihood ratio es:</p>
<p><span class="math inline">\(\chi^2_{diff} = -2(LL_{0} - LL{1})\)</span></p>
<p>Donde,</p>
<ul>
<li>
<span class="math inline">\(LL_{1}\)</span> = es la loglikelihood del modelo de interés</li>
<li>
<span class="math inline">\(LL_{0}\)</span> = es la loglikelihood del modelo nulo</li>
<li>
<span class="math inline">\(\chi^2_{diff}\)</span> = es un valor de <span class="math inline">\(\chi^2\)</span>.</li>
</ul>
<p>Lo que nos entrega esta prueba, es una medida global de discrepancia entre la devianza del modelo nulo, en contraste al modelo de interés. Cuando esta diferencia es muy pequeña, condicional a los grado de libertad, afirmamos que el modelo de interés produce devianzas muy similares a las del modelo que solo contiene al porcentaje de la variable de interés (i.e., el análago del promedio de la regresión lineal). En cambio, cuando esta discrepancia es superior a lo esperado en la distribución de <span class="math inline">\(\chi^2\)</span>, entonces afirmamos que el modelo ajusta de mejor manera a los datos.</p>
<p>Para obtener este indicador, podemos aplicar el siguiente código.</p>
<p><strong>Código 4.1.</strong> Likelihood ratio test</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="co"># Likelihood ratio test</span></span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="fu">anova</span>(m00, m04, <span class="at">test=</span><span class="st">"LRT"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: drop ~ 1
Model 2: drop ~ 1 + zach + zses + int
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1     16609     9967.2                          
2     16606     8045.5  3   1921.7 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Importante">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las pruebas de Likelihood ratio test son muy importantes, porque son aplicables a cualquier modelo estadístico basado en maxima verosimilitud (i.e., maximum likelihood). Estas pueden ser aplicadas sobre diferentes modelos tales como: regresion lineal, modelos multinivel, modelos de regresion logística, modelos generalizados, confirmatory factor analysis, modelos de respuesta al item, entre otros modelos estimados con <em>maximum likelihood</em>.</p>
</div>
</div>
</section><section id="mcfadden-r2" class="level2"><h2 class="anchored" data-anchor-id="mcfadden-r2">McFadden <span class="math inline">\(R^2\)</span>
</h2>
<p>La formula para McFadden R^2, es la siguiente:</p>
<p><span class="math inline">\(\text{McFadden } R^2 = 1 - \frac{LL_{1}}{LL_{0}}\)</span></p>
<p>Donde,</p>
<ul>
<li>
<span class="math inline">\(LL_{1}\)</span> = es la loglikelihood del modelo de interés</li>
<li>
<span class="math inline">\(LL_{0}\)</span> = es la loglikelihood del modelo nulo</li>
</ul>
<p>En esta fórmula se comparamos la máxima verosimilitud no atrribuible al modelo, con la máxima verosimilitud del modelo nulo. En otras palabras, estamos comparando que proporción de máxima verosimilitud es capaz de explicar el modelo que hemos ajustado, en contraste a toda la máxima verosimilitud que puede explicar solo el “promedio” o porcentaje de respuesta sobre los datos observados.</p>
<p>Este indicador, no es precisamente una medida de proporción de varianza explicada, pero se comporta de igual manera. Lo anterior, en el sentido de que a medida que se acerca 1, implica un modelo que ajusta bien a los datos; y a medida que se aleja de 1, implica un modelo que predice a los datos observados en menor medida.</p>
<p>Para obtener el McFadden R^2, vamos a emplear un método manual, y otro empleando a la librería <a href="https://easystats.github.io/performance/"><code>perfomance</code></a> (Lüdecke, et al., 2021).</p>
<p><strong>Código 4.2.</strong> McFadden R^2</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># McFadden R2 via computación manual</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>ll_0 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(m00))</span>
<span id="cb14-3"><a href="#cb14-3"></a>ll_1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(m04))</span>
<span id="cb14-4"><a href="#cb14-4"></a></span>
<span id="cb14-5"><a href="#cb14-5"></a>McFadden_r2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> ll_1<span class="sc">/</span>ll_0</span>
<span id="cb14-6"><a href="#cb14-6"></a>McFadden_r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1928037</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># McFadden via library(performance)</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>performance<span class="sc">::</span><span class="fu">r2_mcfadden</span>(m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># R2 for Generalized Linear Regression
       R2: 0.193
  adj. R2: 0.193</code></pre>
</div>
</div>
</section><section id="horowitz-r2" class="level2"><h2 class="anchored" data-anchor-id="horowitz-r2">Horowitz <span class="math inline">\(R^2\)</span>
</h2>
<p>La formula para Horowitz R^2, es la siguiente:</p>
<p><span class="math inline">\(\text{Horowitz } R^2 = 1 - \frac{LL_{1}-\frac{m}{2}}{LL_{0}}\)</span></p>
<p>Donde,</p>
<ul>
<li>
<span class="math inline">\(LL_{1}\)</span> = es la loglikelihood del modelo de interés</li>
<li>
<span class="math inline">\(LL_{0}\)</span> = es la loglikelihood del modelo nulo</li>
<li>
<span class="math inline">\(m\)</span> = número de parámetros del modelo, excluyendo al intercepto</li>
</ul>
<p><strong>Código 4.3.</strong> Horowitz R^2</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># horowitz_r2 R2 via computación manual</span></span>
<span id="cb18-2"><a href="#cb18-2"></a>ll_0 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(m00))</span>
<span id="cb18-3"><a href="#cb18-3"></a>ll_1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(m04))</span>
<span id="cb18-4"><a href="#cb18-4"></a></span>
<span id="cb18-5"><a href="#cb18-5"></a></span>
<span id="cb18-6"><a href="#cb18-6"></a>m <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(m04) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7"></a>     dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">!=</span> <span class="st">'(Intercept)'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8"></a>     <span class="fu">nrow</span>()</span>
<span id="cb18-9"><a href="#cb18-9"></a></span>
<span id="cb18-10"><a href="#cb18-10"></a>horowitz_r2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (ll_1<span class="sc">-</span>(m<span class="sc">/</span><span class="dv">2</span>))<span class="sc">/</span>ll_0</span>
<span id="cb18-11"><a href="#cb18-11"></a>horowitz_r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1925027</code></pre>
</div>
</div>
<p>Este indicador ajuste, puede ser visto como un McFadden <span class="math inline">\(R^2\)</span> corregido por la cantidad de parámetros que posee el modelo ajustado. En estudios de simulaciones, este indicador es menos sensible al tamaño de la muestra, la cantidad de covariables del modelo, y de la cantidad de categorias presentes en la variable de respuesta (i.e., en modelos de más de dos categorías) (Hemmert et al., 2018). Por esta última razón, se lo considera un indicador más ventajoso en contraste a otros indicadores de pseudo <span class="math inline">\(R^2\)</span> para diferentes modelos logit.</p>
</section><section id="efrons-r2" class="level2"><h2 class="anchored" data-anchor-id="efrons-r2">Efron’s <span class="math inline">\(R^2\)</span>
</h2>
<p>En contraste, Efron’s R^2 sigue la racionalidad del R^2 de la regresión lineal. La formula de este indicador, es la siguiente:</p>
<p><span class="math inline">\(\text{Efron's } R^2 = 1 - \frac{\sum{(y_{i}-\pi_{i})^2}}{\sum{(y_{i}-\hat{y})^2}}\)</span></p>
<p>Donde,</p>
<ul>
<li>
<span class="math inline">\(y_{i}\)</span> = es el valor observado <span class="math inline">\(y\)</span>, para cada fila <span class="math inline">\(i\)</span>
</li>
<li>
<span class="math inline">\(\pi_{i}\)</span> = es el valor esperado <span class="math inline">\(y\)</span>, para cada fila <span class="math inline">\(i\)</span>, dado el modelo de interés</li>
<li>
<span class="math inline">\(\hat{y}\)</span> = es el valor esperado <span class="math inline">\(y\)</span>, por ejemplo <span class="math inline">\(\hat{y} = \frac{\sum{y_{i}}}{n}\)</span>
</li>
</ul>
<p><strong>Código 4.4.</strong> Efron’s R^2</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># Efron R^2 via computación manual</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>y_hat <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">predict</span>(m04, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb20-3"><a href="#cb20-3"></a>y <span class="ot">&lt;-</span> data_model<span class="sc">$</span>drop</span>
<span id="cb20-4"><a href="#cb20-4"></a>pr_y <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb20-5"><a href="#cb20-5"></a></span>
<span id="cb20-6"><a href="#cb20-6"></a>efron_r2 <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> (<span class="fu">sum</span>((y <span class="sc">-</span> y_hat)<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">/</span> (<span class="fu">sum</span>((y <span class="sc">-</span> pr_y)<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb20-7"><a href="#cb20-7"></a>efron_r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1276261</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="co"># Efron R^2 via library(perfomance)</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>performance<span class="sc">::</span><span class="fu">r2_efron</span>(m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1276261</code></pre>
</div>
</div>
</section><section id="mckelvey-zavoina-pseudo-r2" class="level2"><h2 class="anchored" data-anchor-id="mckelvey-zavoina-pseudo-r2">McKelvey &amp; Zavoina Pseudo <span class="math inline">\(R^2\)</span>
</h2>
<p>McKelvey &amp; Zavoina Pseudo R^2 puede ser atractivo, porque sigue la lógica de producir una proporción de varianza explicada. En esta aproximación, se asumen que podemos realizar la siguiente descomposición:</p>
<p><span class="math display">\[S_{T}^2 = S_{R}^2 + S_{E}^2\]</span></p>
<p>Donde,</p>
<p><span class="math inline">\(S_{T}^2\)</span> es la suma de cuadrados totales (i.e., la varianza total). <span class="math inline">\(S_{E}^2\)</span> es la suma de cuadrados generada por el modelo <span class="math inline">\(S_{R}^2\)</span> es la suma de cuadrados del error</p>
<p>Para el caso de los modelos de regresión logística la varianza residual de <span class="math inline">\(y\)</span> es fija y se expresa con el siguiente término <span class="math inline">\(\pi^2/3\)</span>.</p>
<p>De esta forma el <span class="math inline">\(R^2\)</span> de McKelvey &amp; Zavoina (1975) puede ser expresado para la regresión logística de la siguiente forma:</p>
<ul>
<li>Suma de cuadrados esperadas dado el modelo:</li>
</ul>
<p><span class="math inline">\(S_{E}^2 = \sum{(\hat{y}_{i}}-\hat{\bar{y}})^2\)</span></p>
<ul>
<li>Suma de cuadrados residuales:</li>
</ul>
<p><span class="math inline">\(S_{R}^2 = n*\pi^2/3\)</span></p>
<ul>
<li>Suma de cuadrados totales:</li>
</ul>
<p><span class="math inline">\(S_{T}^2 = \sum{(\hat{y}_{i}}-\hat{\bar{y}})^2 + (n*\pi^2/3)\)</span></p>
<p>Con los términos anteriores podemos construir el R^2 esperado:</p>
<p><span class="math inline">\(\hat{R^2} = \frac{S_{E}^2}{S_{T}^2}=\frac{\sum{(\hat{y}_{i}}-\hat{\bar{y}})^2}{\sum{(\hat{y}_{i}}-\hat{\bar{y}})^2 + (n*\pi^2/3)}\)</span></p>
<p><strong>Código 4.5.</strong> McKelvey &amp; Zavoina Pseudo <span class="math inline">\(R^2\)</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># McKelvey &amp; Zavoina Pseudo R^2 via computación manual (método 1)</span></span>
<span id="cb24-2"><a href="#cb24-2"></a></span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="do">## términos</span></span>
<span id="cb24-4"><a href="#cb24-4"></a>y_hat <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">predict</span>(m04, <span class="at">type =</span> <span class="st">"link"</span>)</span>
<span id="cb24-5"><a href="#cb24-5"></a>bar_y_hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(y_hat)</span>
<span id="cb24-6"><a href="#cb24-6"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(data_model)</span>
<span id="cb24-7"><a href="#cb24-7"></a>sigma_2 <span class="ot">&lt;-</span> pi<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">3</span></span>
<span id="cb24-8"><a href="#cb24-8"></a></span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="co"># suma de cuadrados del modelo</span></span>
<span id="cb24-10"><a href="#cb24-10"></a>sse <span class="ot">&lt;-</span> <span class="fu">sum</span>((y_hat <span class="sc">-</span> bar_y_hat)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb24-11"><a href="#cb24-11"></a><span class="co"># suma de cuadrados totakes</span></span>
<span id="cb24-12"><a href="#cb24-12"></a>sst <span class="ot">&lt;-</span> sse <span class="sc">+</span> n <span class="sc">*</span> sigma_2</span>
<span id="cb24-13"><a href="#cb24-13"></a></span>
<span id="cb24-14"><a href="#cb24-14"></a>mzr2_m1 <span class="ot">&lt;-</span> sse <span class="sc">/</span> sst</span>
<span id="cb24-15"><a href="#cb24-15"></a>mzr2_m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4982506</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># McKelvey &amp; Zavoina Pseudo R^2 via computación manual (método 2)</span></span>
<span id="cb26-2"><a href="#cb26-2"></a></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="co"># formula para obetener varianza de la población (y no de la muestra)</span></span>
<span id="cb26-4"><a href="#cb26-4"></a>var_pop <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb26-5"><a href="#cb26-5"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb26-6"><a href="#cb26-6"></a>var_pop <span class="ot">&lt;-</span> <span class="fu">var</span>(x) <span class="sc">*</span> (n <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">/</span>n</span>
<span id="cb26-7"><a href="#cb26-7"></a><span class="fu">return</span>(var_pop)</span>
<span id="cb26-8"><a href="#cb26-8"></a>}</span>
<span id="cb26-9"><a href="#cb26-9"></a></span>
<span id="cb26-10"><a href="#cb26-10"></a>var_star_y <span class="ot">&lt;-</span> <span class="fu">var_pop</span>(y_hat)</span>
<span id="cb26-11"><a href="#cb26-11"></a></span>
<span id="cb26-12"><a href="#cb26-12"></a>var_star_t <span class="ot">&lt;-</span> <span class="fu">var_pop</span>(y_hat) <span class="sc">+</span> (pi<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">3</span></span>
<span id="cb26-13"><a href="#cb26-13"></a></span>
<span id="cb26-14"><a href="#cb26-14"></a>mzr2_m2 <span class="ot">&lt;-</span> var_star_y<span class="sc">/</span>var_star_t</span>
<span id="cb26-15"><a href="#cb26-15"></a>mzr2_m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4982506</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="co"># McKelvey &amp; Zavoina Pseudo R^2 via performance::r2_mckelvey() (método 3)</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>mzr2_m3 <span class="ot">&lt;-</span> performance<span class="sc">::</span><span class="fu">r2_mckelvey</span>(m04)</span>
<span id="cb28-3"><a href="#cb28-3"></a>mzr2_m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>McKelvey's R2 
    0.4982506 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="co"># Comparación de métodos de calculos empleados</span></span>
<span id="cb30-2"><a href="#cb30-2"></a><span class="fu">data.frame</span>(</span>
<span id="cb30-3"><a href="#cb30-3"></a><span class="at">method =</span> <span class="fu">c</span>(<span class="st">'via SSE'</span>, <span class="st">'via Varianza'</span>, <span class="st">'performance::r2_mckelvey'</span>),</span>
<span id="cb30-4"><a href="#cb30-4"></a><span class="at">MZ_R2 =</span> <span class="fu">c</span>(mzr2_m1, mzr2_m2, mzr2_m3)</span>
<span id="cb30-5"><a href="#cb30-5"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="#cb30-6"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(., <span class="at">digits =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">method</th>
<th style="text-align: right;">MZ_R2</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">via SSE</td>
<td style="text-align: right;">0.4982506</td>
</tr>
<tr class="even">
<td style="text-align: left;">via Varianza</td>
<td style="text-align: right;">0.4982506</td>
</tr>
<tr class="odd">
<td style="text-align: left;">performance::r2_mckelvey</td>
<td style="text-align: right;">0.4982506</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="indicadores-de-ajuste" class="level2"><h2 class="anchored" data-anchor-id="indicadores-de-ajuste">Indicadores de ajuste</h2>
<p>Una forma de obtener cada uno de estos indicadores de ajuste con una sola función es empleando a la función <code><a href="https://blorr.rsquaredacademy.com/reference/blr_model_fit_stats.html">blorr::blr_model_fit_stats()</a></code>. Además, podemos emplear la función <code><a href="https://blorr.rsquaredacademy.com/reference/blr_multi_model_fit_stats.html">blorr::blr_multi_model_fit_stats</a></code>, con la cual podemos comparar los indicadores de ajuste de varios modelos. Finalmente, empleando a <code><a href="https://generics.r-lib.org/reference/glance.html">broom::glance()</a></code> podemos obtener algunos de los indicadores que se producen con <code>summary(model)</code>, pero en formato tabla, lo cual nos puede servir para extraer estadísticos particulares del modelo (e.g., loglikelihood, deviance, AIC, BIC).</p>
<p><strong>Código 4.6.</strong> Indicadores de ajuste</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># indicadores de ajuste con blorr</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>blorr<span class="sc">::</span><span class="fu">blr_model_fit_stats</span>(m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              Model Fit Statistics                                
---------------------------------------------------------------------------------
Log-Lik Intercept Only:     -4983.621    Log-Lik Full Model:            -4022.761 
Deviance(16606):             8045.521    LR(3):                          1921.721 
                                         Prob &gt; LR:                         0.000 
MCFadden's R2                   0.193    McFadden's Adj R2:                 0.192 
ML (Cox-Snell) R2:              0.109    Cragg-Uhler(Nagelkerke) R2:        0.242 
McKelvey &amp; Zavoina's R2:        0.498    Efron's R2:                        0.128 
Count R2:                       0.911    Adj Count R2:                      0.001 
BIC:                         8084.392    AIC:                            8053.521 
---------------------------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># comparacion de modelos</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>blorr<span class="sc">::</span><span class="fu">blr_multi_model_fit_stats</span>(m00, m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               Measures   Model 1   Model 2
loglik_null      Log-Lik Intercept Only -4983.621 -4983.621
loglik_model         Log-Lik Full Model -4983.621 -4022.761
m_deviance                     Deviance  9967.242  8045.521
lr_ratio                             LR     0.000  1921.721
lr_pval                       Prob &gt; LR     1.000     0.000
mcfadden                  MCFadden's R2     0.000     0.193
adj_mcfadden          McFadden's Adj R2     0.000     0.192
m_aic                 ML (Cox-Snell) R2  9969.242  8053.521
cox_snell    Cragg-Uhler(Nagelkerke) R2     0.000     0.109
m_bic           McKelvey &amp; Zavoina's R2  9976.960  8084.392
mckelvey                     Efron's R2     0.000     0.498
effron                         Count R2     0.000     0.128
nagelkerke                 Adj Count R2     0.000     0.242
count_r2                            AIC     0.911     0.911
count_adj                           BIC     0.000     0.001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># indicadores de ajuste con broom</span></span>
<span id="cb35-2"><a href="#cb35-2"></a>broom<span class="sc">::</span><span class="fu">glance</span>(m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
          &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
1         9967.   16609 -4023. 8054. 8084.    8046.       16606 16610</code></pre>
</div>
</div>
</section><section id="qué-indicador-de-pseudo-r-emplear" class="level2"><h2 class="anchored" data-anchor-id="qué-indicador-de-pseudo-r-emplear">¿Qué indicador de Pseudo R emplear?</h2>
<p>Si comparamos los diferentes indicadores de pseudo <span class="math inline">\(R^2\)</span> empleados en regresión logística podemos ver que estos difieren en tamaño de manera importante (ver tabla siguiente.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Código para obtener cada uno de los pseudo R^2</summary><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb37-2"><a href="#cb37-2"></a><span class="at">pseudo_r2 =</span> <span class="fu">c</span>(<span class="st">'Effron'</span>, <span class="st">'McFadden'</span>, <span class="st">'Horowitz'</span>, <span class="st">'McKelvey &amp; Zavoina'</span>),</span>
<span id="cb37-3"><a href="#cb37-3"></a><span class="at">estimate =</span> <span class="fu">c</span>( </span>
<span id="cb37-4"><a href="#cb37-4"></a><span class="fu">as.numeric</span>(performance<span class="sc">::</span><span class="fu">r2_efron</span>(m04)),</span>
<span id="cb37-5"><a href="#cb37-5"></a><span class="fu">as.numeric</span>(performance<span class="sc">::</span><span class="fu">r2_mcfadden</span>(m04)<span class="sc">$</span>R2),</span>
<span id="cb37-6"><a href="#cb37-6"></a>horowitz_r2,</span>
<span id="cb37-7"><a href="#cb37-7"></a><span class="fu">as.numeric</span>(performance<span class="sc">::</span><span class="fu">r2_mckelvey</span>(m04))),</span>
<span id="cb37-8"><a href="#cb37-8"></a><span class="at">racionalidad =</span> <span class="fu">c</span>(</span>
<span id="cb37-9"><a href="#cb37-9"></a><span class="st">'Reducción de predichos'</span>,</span>
<span id="cb37-10"><a href="#cb37-10"></a><span class="st">'Reducción de devianza'</span>,</span>
<span id="cb37-11"><a href="#cb37-11"></a><span class="st">'Reducción de devianza, corregido por la cantidad de parámetros'</span>,</span>
<span id="cb37-12"><a href="#cb37-12"></a><span class="st">'Reducción de varianza latente'</span></span>
<span id="cb37-13"><a href="#cb37-13"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb37-14"><a href="#cb37-14"></a><span class="fu">arrange</span>(estimate) <span class="sc">%&gt;%</span></span>
<span id="cb37-15"><a href="#cb37-15"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(., <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">caption =</span> <span class="st">'Tabla 1: comparación de R^2 para modelo `m04`'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Tabla 1: comparación de R^2 para modelo <code>m04</code>
</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 9%">
<col style="width: 69%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">pseudo_r2</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: left;">racionalidad</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Effron</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: left;">Reducción de predichos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Horowitz</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;">Reducción de devianza, corregido por la cantidad de parámetros</td>
</tr>
<tr class="odd">
<td style="text-align: left;">McFadden</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;">Reducción de devianza</td>
</tr>
<tr class="even">
<td style="text-align: left;">McKelvey &amp; Zavoina</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: left;">Reducción de varianza latente</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>No existe un consenso transversal en la literatura, respecto a cual indicador <span class="math inline">\(R^2\)</span> es más adecuado (O’Connel et al, 2019). No obstante, Menard (2000) plantea que McFadden <span class="math inline">\(R^2\)</span> puede ser preferible por dos razones: a) este es un indicador que puede ser interpretado como una medida de reducción de error, y b) que este indicador es insensible a la tasa de prevalencia del evento de interés, es decir el <span class="math inline">\(Pr(y = 1)\)</span>. Por su parte Hemmert et al.&nbsp;(2018), recomienda al indicador de pseudo de R^2 de Horowitz (1982), debido a que este indicador es menos sensible al tamaño muestral, y la distribución de categorias de la variable de respuesta.</p>
<p>No obstante, si el uso de estos indicadores, es solo comparación entre modelos ajustados sobre los mismos datos, y sobre la misma variable dependiente, cualquiera de estos indicadores debiera al propósito de ayudar a la selección de modelos.</p>
<p>O’Connel et al.&nbsp;(2019) por su parte, plantea que el indicador McFadden <span class="math inline">\(R^2\)</span> es uno de los indicadores más intuitivos como medida de mejora de ajuste, dado el modelo de interés.</p>
<p>De todas formas, lo más importante a tener en cuenta, es el propósito para el cual se quiera emplear uno de estos indicadores, e indicar claramente cual es el indicador que esta siendo empleado en el reporte de resultados del manuscrito (Menard, 2000; Hemmert et al., 2018). En otras palabras, la recomendación a seguir es siempre reportar el ajuste del modelo, indicando explícitamente cuál de estos indicadores es el reportado.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Tip">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>En el reporte de resultado de regresión logística, en el primer párrafo de descripción de resultados sobre el ajuste de modelo, se requiere indicar claramente el indicador de pseudo <span class="math inline">\(R^2\)</span> que esta siendo reportado.</p>
</div>
</div>
</section><section id="calidad-de-la-clasificación" class="level2"><h2 class="anchored" data-anchor-id="calidad-de-la-clasificación">Calidad de la clasificación</h2>
<p>Uno de los indicadores más sencillos de calidad de clasificación es la proporción de casos predichos en contraste a la cantidad de observaciones. Este indicador puede ser obtenido de variadas maneras. La forma más sencilla, consiste en producir una tabla de contingencia entre los valores predichos, y los valores observados. Se suman los valores correctamente predichos de cada categoria, y se dividen por la cantidad de observaciones.</p>
<p>Coincide, que para el caso de regresión logistica, este es el mismo indicador de cantidad de clasificaciones correctas o <em>Count</em> <span class="math inline">\(R^2\)</span>.</p>
<p>Otro indicador de clasificación, es el indicador <span class="math inline">\(tau_{p}\)</span> Menard (2000, 2001). Este es un indicador, basado en clasificaciones basadas en probabilidades no simétricas (Ma &amp; Redmond, 1995). Este indicador consiste en la proporción de clasificaciones correctas ajustando por las probabilidades a priori. Es decir, la tasa de prevalencia del evento, previo a que tengamos información de las covariables. Este segundo término se obtiene como las probabilidades marginales de la distribución de referencia (i.e., el porcentaje del evento de interes, obtenido desde la variable e respuesta). En la literatura de clasificación este indicador tambien se lo conoce como Klecka’s <span class="math inline">\(\tau\)</span> (Klecka, 1980). De forma análoga, tambien es posible producir <span class="math inline">\(\tau_{e}\)</span>, el cual ajusta las clasificaciones empleando una clasificación al azar. La cual, en el caso del modelo de regresión logística es equivalente a .5 (1/cantidad de valores posibles).</p>
<p>A continuación, incluimos código para producir a los indicadores de:</p>
<ul>
<li>count <span class="math inline">\(R^2\)</span> = Porcentaje de clasificacion correcta <code>count_r2</code>
</li>
<li>Accuracy = Porcentaje de clasificacion correcta, sobre el total <code>accuracy</code>
</li>
<li>
<span class="math inline">\(\tau_{p}\)</span> = Porcentaje de classifiación correcta, ajustado por la prevalencia (<span class="math inline">\(\tau_{p}\)</span>)</li>
<li>
<span class="math inline">\(\tau_{e}\)</span> = Porcentaje de classifiación correcta, ajustado por azar (<span class="math inline">\(\tau_{e}\)</span>)</li>
<li>
<span class="math inline">\(\lambda_{p}\)</span> Porcentaje de classifiación correcta, ajustado por categoria modal (<span class="math inline">\(\lambda_{p}\)</span>)</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Importante">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es importante señalar que los indicadores de clasificación no son calculados por defecto por diferentes paquetes estadísticos. Y por tanto, hay menos acuerdo en la literatura respecto a cual de estos indicadores es más adecuado reportar (O’Connel et al, 2019). Menard (2000) recomienda al indicador de <span class="math inline">\(\tau_{p}\)</span>, y al count <span class="math inline">\(R^2\)</span> o porcentaje de clasificación correctas por sobre el total. En esta guia, emplearemos este indicador para crear el reporte de resultados.</p>
</div>
</div>
<p><strong>Código 4.7.</strong> Indicadores de clasificación</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># count pseudo R2</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>blorr<span class="sc">::</span><span class="fu">blr_model_fit_stats</span>(m04)<span class="sc">$</span>count_r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9111379</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># accuracy</span></span>
<span id="cb40-2"><a href="#cb40-2"></a>blorr<span class="sc">::</span><span class="fu">blr_confusion_matrix</span>(m04)<span class="sc">$</span>accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9111379</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># calculos manuales</span></span>
<span id="cb42-2"><a href="#cb42-2"></a>y_obs <span class="ot">&lt;-</span> m04<span class="sc">$</span>y</span>
<span id="cb42-3"><a href="#cb42-3"></a>y_hat <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">if_else</span>(<span class="fu">predict</span>(m04, <span class="at">type =</span> <span class="st">"response"</span>) <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb42-4"><a href="#cb42-4"></a>n_obs <span class="ot">&lt;-</span> <span class="fu">length</span>(y_obs)</span>
<span id="cb42-5"><a href="#cb42-5"></a></span>
<span id="cb42-6"><a href="#cb42-6"></a>f_ii <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">if_else</span>(y_obs <span class="sc">==</span> y_hat,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb42-7"><a href="#cb42-7"></a></span>
<span id="cb42-8"><a href="#cb42-8"></a><span class="do">## count pseudo R2</span></span>
<span id="cb42-9"><a href="#cb42-9"></a>count_r2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(f_ii)<span class="sc">/</span>n_obs</span>
<span id="cb42-10"><a href="#cb42-10"></a>count_r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9111379</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="do">## tau_e Ma &amp; Redmond (1995)</span></span>
<span id="cb44-2"><a href="#cb44-2"></a>p_o  <span class="ot">&lt;-</span> <span class="fu">sum</span>(f_ii)<span class="sc">/</span>n_obs</span>
<span id="cb44-3"><a href="#cb44-3"></a>p_re <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb44-4"><a href="#cb44-4"></a><span class="co"># Note: clasification by chance</span></span>
<span id="cb44-5"><a href="#cb44-5"></a></span>
<span id="cb44-6"><a href="#cb44-6"></a>tau_e <span class="ot">&lt;-</span> (p_o <span class="sc">-</span> p_re)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_re)</span>
<span id="cb44-7"><a href="#cb44-7"></a>tau_e</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8222757</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="do">## tau p Ma &amp; Redmond (1995)</span></span>
<span id="cb46-2"><a href="#cb46-2"></a>p_o  <span class="ot">&lt;-</span> <span class="fu">sum</span>(f_ii)<span class="sc">/</span>n_obs</span>
<span id="cb46-3"><a href="#cb46-3"></a>p_rp <span class="ot">&lt;-</span> <span class="fu">mean</span>(y_obs) </span>
<span id="cb46-4"><a href="#cb46-4"></a><span class="co"># Note: marginal distribution of the reference data</span></span>
<span id="cb46-5"><a href="#cb46-5"></a></span>
<span id="cb46-6"><a href="#cb46-6"></a>tau_p <span class="ot">&lt;-</span> (p_o <span class="sc">-</span> p_rp)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p_rp)</span>
<span id="cb46-7"><a href="#cb46-7"></a>tau_p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9024648</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="do">## tau p Klecka's (1980)</span></span>
<span id="cb48-2"><a href="#cb48-2"></a>n_p <span class="ot">&lt;-</span> <span class="fu">sum</span>(y_obs)</span>
<span id="cb48-3"><a href="#cb48-3"></a>n_q <span class="ot">&lt;-</span> n_obs <span class="sc">-</span> <span class="fu">sum</span>(y_obs)</span>
<span id="cb48-4"><a href="#cb48-4"></a></span>
<span id="cb48-5"><a href="#cb48-5"></a>tau_num  <span class="ot">&lt;-</span> <span class="fu">sum</span>(f_ii) <span class="sc">-</span> pr_y<span class="sc">*</span>(n_p <span class="sc">+</span> n_q)</span>
<span id="cb48-6"><a href="#cb48-6"></a>tau_den <span class="ot">&lt;-</span> n_obs <span class="sc">-</span> pr_y<span class="sc">*</span>(n_p <span class="sc">+</span> n_q)</span>
<span id="cb48-7"><a href="#cb48-7"></a>tau_p <span class="ot">&lt;-</span> tau_num<span class="sc">/</span>tau_den</span>
<span id="cb48-8"><a href="#cb48-8"></a>tau_p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9024648</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="do">## tau_p Menard (2001)</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>errors_without_model <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> p_rp</span>
<span id="cb50-3"><a href="#cb50-3"></a>errors_with_model <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span>p_o</span>
<span id="cb50-4"><a href="#cb50-4"></a></span>
<span id="cb50-5"><a href="#cb50-5"></a>tau_p <span class="ot">&lt;-</span> (errors_without_model <span class="sc">-</span> errors_with_model)<span class="sc">/</span>errors_without_model</span>
<span id="cb50-6"><a href="#cb50-6"></a>tau_p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9024648</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="do">## lambda p (Menard, 2000)</span></span>
<span id="cb52-2"><a href="#cb52-2"></a>n_mode <span class="ot">&lt;-</span> <span class="fu">sum</span>(y_obs)</span>
<span id="cb52-3"><a href="#cb52-3"></a>lambda_num  <span class="ot">&lt;-</span> n_obs <span class="sc">-</span> <span class="fu">sum</span>(f_ii)</span>
<span id="cb52-4"><a href="#cb52-4"></a>lambda_den  <span class="ot">&lt;-</span> n_obs <span class="sc">-</span> n_mode</span>
<span id="cb52-5"><a href="#cb52-5"></a>lambda_p <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> lambda_num<span class="sc">/</span>lambda_den</span>
<span id="cb52-6"><a href="#cb52-6"></a>lambda_p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9024648</code></pre>
</div>
</div>
</section></section><section id="tabla-de-resultados" class="level1"><h1>5. Tabla de resultados</h1>
<p>Para producir una tabla general de resultados vamos a emplear dos estrategias. Una de ellas, consiste en emplear tablas de que producen librerias. En este caso, vamos a emplear las tablas que produce las funciones <code><a href="https://rdrr.io/pkg/texreg/man/screenreg.html">texreg::screenreg()</a></code>, <code><a href="https://blorr.rsquaredacademy.com/reference/blr_regress.html">blorr::blr_regress()</a></code>, y <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code>. Luego, como segunda estrategia, vamos a crear una tabla con los contenidos que queremos que contenga la tabla. Comúnmente, una tabla de resultados de regresión logística posee: - los nombres de la covariables - los coeficientes de regresión logística - los errores estandares de los coeficientes - los resultados de la prueba estadística sobre los coeficientes - incluyendo o no, al resultado de esta prueba - los valores p, o en su reemplazo a los p valor resumidos empleando <code>*</code> - los coeficientes en <em>odds ratio</em>.</p>
<p>Con los siguientes códigos vamos a producir la tabla general.</p>
<p><strong>Código 5.1.</strong> tabla de resultados</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="co"># metodo 1: screenreg</span></span>
<span id="cb54-2"><a href="#cb54-2"></a>texreg<span class="sc">::</span><span class="fu">screenreg</span>(</span>
<span id="cb54-3"><a href="#cb54-3"></a>  <span class="fu">list</span>(m04), </span>
<span id="cb54-4"><a href="#cb54-4"></a>  <span class="at">single.row =</span> <span class="cn">TRUE</span></span>
<span id="cb54-5"><a href="#cb54-5"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===================================
                Model 1            
-----------------------------------
(Intercept)        -3.17 (0.05) ***
zach               -1.17 (0.05) ***
zses               -0.86 (0.05) ***
int                -0.21 (0.05) ***
-----------------------------------
AIC              8053.52           
BIC              8084.39           
Log Likelihood  -4022.76           
Deviance         8045.52           
Num. obs.       16610              
===================================
*** p &lt; 0.001; ** p &lt; 0.01; * p &lt; 0.05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="co"># metodo 2: blorr</span></span>
<span id="cb56-2"><a href="#cb56-2"></a>blorr<span class="sc">::</span><span class="fu">blr_regress</span>(m04, <span class="at">odd_conf_limit =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             Model Overview                               
-------------------------------------------------------------------------
Data Set    Resp Var     Obs.    Df. Model    Df. Residual    Convergence 
-------------------------------------------------------------------------
  data        drop      16610      16609         16606           TRUE     
-------------------------------------------------------------------------

                    Response Summary                     
--------------------------------------------------------
Outcome        Frequency        Outcome        Frequency 
--------------------------------------------------------
   0             15133             1             1477    
--------------------------------------------------------

                   Maximum Likelihood Estimates                    
------------------------------------------------------------------
 Parameter     DF    Estimate    Std. Error    z value     Pr(&gt;|z|) 
------------------------------------------------------------------
(Intercept)    1     -3.1743        0.0540    -58.8165      0.0000 
   zach        1     -1.1744        0.0548    -21.4362      0.0000 
   zses        1     -0.8570        0.0540    -15.8635      0.0000 
    int        1     -0.2093        0.0514     -4.0744      0.0000 
------------------------------------------------------------------

                   Odds Ratio Estimates                    
----------------------------------------------------------
 Effects          Estimate           95% Wald Conf. Limit 
----------------------------------------------------------
   zach            0.3090           0.2770          0.3434 
   zses            0.4244           0.3814          0.4713 
   int             0.8111           0.7326          0.8960 
----------------------------------------------------------

 Association of Predicted Probabilities and Observed Responses  
---------------------------------------------------------------
% Concordant          0.8200          Somers' D        0.6400   
% Discordant          0.1800          Gamma            0.6400   
% Tied                0.0000          Tau-a            0.1037   
Pairs                22351441         c                0.8200   
---------------------------------------------------------------</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="co"># metodo 3: broom::tidy()</span></span>
<span id="cb58-2"><a href="#cb58-2"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(m04) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3"></a><span class="fu">mutate</span>(<span class="at">OR =</span> <span class="fu">exp</span>(estimate))  <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(., <span class="at">digits =</span> <span class="dv">3</span>)      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">OR</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-3.174</td>
<td style="text-align: right;">0.054</td>
<td style="text-align: right;">-58.817</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.042</td>
</tr>
<tr class="even">
<td style="text-align: left;">zach</td>
<td style="text-align: right;">-1.174</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">-21.436</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.309</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zses</td>
<td style="text-align: right;">-0.857</td>
<td style="text-align: right;">0.054</td>
<td style="text-align: right;">-15.863</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.424</td>
</tr>
<tr class="even">
<td style="text-align: left;">int</td>
<td style="text-align: right;">-0.209</td>
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">-4.074</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.811</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>El código siguiente emplea a los resultados parciales que genera <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code>. La ventaja que posee esta fucnión consiste en que el producto de su aplicación es una tabla de resultados, o <em>data_frame</em>. Y como tal, nos permite realizar calculos sobre ella. Empleando esta última propiedad, cambiamos el formato de los resultados entregados, de modo que la tabla final se asemeje a los contenidos de una tabla de resultados de formato de manuscrito.</p>
<p><strong>Código 5.2.</strong> tabla de resultados via <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="co"># metodo 4: broom::tidy() y edición de campus</span></span>
<span id="cb59-2"><a href="#cb59-2"></a></span>
<span id="cb59-3"><a href="#cb59-3"></a><span class="do">## función para decinir 2 decimales</span></span>
<span id="cb59-4"><a href="#cb59-4"></a>decimales <span class="ot">&lt;-</span> <span class="cf">function</span> (x, k) {</span>
<span id="cb59-5"><a href="#cb59-5"></a>    <span class="fu">format</span>(<span class="fu">round</span>(x, k), <span class="at">nsmall =</span> k)</span>
<span id="cb59-6"><a href="#cb59-6"></a>}</span>
<span id="cb59-7"><a href="#cb59-7"></a></span>
<span id="cb59-8"><a href="#cb59-8"></a></span>
<span id="cb59-9"><a href="#cb59-9"></a><span class="do">## tabla con estimados</span></span>
<span id="cb59-10"><a href="#cb59-10"></a>tabla_1 <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(m04) <span class="sc">%&gt;%</span></span>
<span id="cb59-11"><a href="#cb59-11"></a><span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">case_when</span>(</span>
<span id="cb59-12"><a href="#cb59-12"></a>term <span class="sc">==</span> <span class="st">'(Intercept)'</span> <span class="sc">~</span> <span class="st">'intercepto'</span>,</span>
<span id="cb59-13"><a href="#cb59-13"></a>term <span class="sc">==</span> <span class="st">'zach'</span>        <span class="sc">~</span> <span class="st">'logro académico (puntaje z)'</span>,</span>
<span id="cb59-14"><a href="#cb59-14"></a>term <span class="sc">==</span> <span class="st">'zses'</span>        <span class="sc">~</span> <span class="st">'nivel socioeconómico (puntaje z)'</span>,</span>
<span id="cb59-15"><a href="#cb59-15"></a>term <span class="sc">==</span> <span class="st">'int'</span>         <span class="sc">~</span> <span class="st">'interacción'</span></span>
<span id="cb59-16"><a href="#cb59-16"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb59-17"><a href="#cb59-17"></a><span class="fu">mutate</span>(<span class="at">e  =</span> <span class="fu">decimales</span>(estimate, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb59-18"><a href="#cb59-18"></a><span class="fu">mutate</span>(<span class="at">se =</span> <span class="fu">paste0</span>(<span class="st">'('</span>, <span class="fu">decimales</span>(std.error, <span class="dv">2</span>), <span class="st">')'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb59-19"><a href="#cb59-19"></a><span class="fu">mutate</span>(<span class="at">star =</span> <span class="fu">case_when</span>(</span>
<span id="cb59-20"><a href="#cb59-20"></a>p.value <span class="sc">&lt;</span>  .<span class="dv">001</span> <span class="sc">~</span> <span class="st">'***'</span>,</span>
<span id="cb59-21"><a href="#cb59-21"></a>p.value <span class="sc">&lt;</span>  .<span class="dv">01</span>  <span class="sc">~</span> <span class="st">'** '</span>,</span>
<span id="cb59-22"><a href="#cb59-22"></a>p.value <span class="sc">&lt;</span>  .<span class="dv">05</span>  <span class="sc">~</span> <span class="st">'*  '</span>,</span>
<span id="cb59-23"><a href="#cb59-23"></a>p.value <span class="sc">&gt;=</span> .<span class="dv">05</span>  <span class="sc">~</span> <span class="st">'   '</span></span>
<span id="cb59-24"><a href="#cb59-24"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb59-25"><a href="#cb59-25"></a><span class="fu">mutate</span>(<span class="at">odds_ratio =</span> <span class="fu">decimales</span>(<span class="fu">exp</span>(estimate),<span class="dv">2</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb59-26"><a href="#cb59-26"></a><span class="fu">mutate</span>(<span class="at">reverse_odds_ratio =</span> <span class="fu">decimales</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">exp</span>(estimate),<span class="dv">2</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb59-27"><a href="#cb59-27"></a><span class="fu">mutate</span>(<span class="at">odds_ratio =</span> <span class="fu">case_when</span>(</span>
<span id="cb59-28"><a href="#cb59-28"></a>text <span class="sc">==</span> <span class="st">'intercepto'</span> <span class="sc">~</span> <span class="st">''</span>,</span>
<span id="cb59-29"><a href="#cb59-29"></a>text <span class="sc">!=</span> <span class="st">'intercepto'</span> <span class="sc">~</span> odds_ratio</span>
<span id="cb59-30"><a href="#cb59-30"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb59-31"><a href="#cb59-31"></a><span class="fu">mutate</span>(<span class="at">reverse_odds_ratio =</span> <span class="fu">case_when</span>(</span>
<span id="cb59-32"><a href="#cb59-32"></a>text <span class="sc">==</span> <span class="st">'intercepto'</span> <span class="sc">~</span> <span class="st">''</span>,</span>
<span id="cb59-33"><a href="#cb59-33"></a>text <span class="sc">!=</span> <span class="st">'intercepto'</span> <span class="sc">~</span> reverse_odds_ratio</span>
<span id="cb59-34"><a href="#cb59-34"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb59-35"><a href="#cb59-35"></a>dplyr<span class="sc">::</span><span class="fu">select</span>(text, e, se, star, odds_ratio, reverse_odds_ratio)</span>
<span id="cb59-36"><a href="#cb59-36"></a></span>
<span id="cb59-37"><a href="#cb59-37"></a></span>
<span id="cb59-38"><a href="#cb59-38"></a>tabla_1 <span class="sc">%&gt;%</span></span>
<span id="cb59-39"><a href="#cb59-39"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(., <span class="at">digits =</span> <span class="dv">2</span>)     </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 40%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">text</th>
<th style="text-align: left;">e</th>
<th style="text-align: left;">se</th>
<th style="text-align: left;">star</th>
<th style="text-align: left;">odds_ratio</th>
<th style="text-align: left;">reverse_odds_ratio</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercepto</td>
<td style="text-align: left;">-3.17</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">logro académico (puntaje z)</td>
<td style="text-align: left;">-1.17</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;">0.31</td>
<td style="text-align: left;">3.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nivel socioeconómico (puntaje z)</td>
<td style="text-align: left;">-0.86</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">2.36</td>
</tr>
<tr class="even">
<td style="text-align: left;">interacción</td>
<td style="text-align: left;">-0.21</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;">0.81</td>
<td style="text-align: left;">1.23</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="do">## guardar tabla a excel</span></span>
<span id="cb60-2"><a href="#cb60-2"></a>tabla_1 <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3"></a>openxlsx<span class="sc">::</span><span class="fu">write.xlsx</span>(., </span>
<span id="cb60-4"><a href="#cb60-4"></a>  <span class="st">'tabla_1_resultados.xlsx'</span>, </span>
<span id="cb60-5"><a href="#cb60-5"></a>  <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="figura" class="level1"><h1>6. Figura</h1>
<p>Empleamos el siguiente código para producir una figura que emplea a las probabilidades condicionales, generadas con los resultados del modelo a ± 2 DS para nivel socioeconómico de las familias, y para logro académico de los estudiantes.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Nota">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>El código siguiente es una versión adaptada del código que empleamos en la guía anterior (ver <a href="https://www.dropbox.com/scl/fi/v97na2zc4qdrs97oaa9og/Osborne_2012_output_r_anotado.html?rlkey=g8m8741n1x7bpkndq9ixpobz8&amp;dl=1">link</a>). En este caso, empleamos <em>labels</em> en castellano; mientras que la guía anterior nos enfocamos en reproducir los pasos empleados por Osborne (2012).</p>
</div>
</div>
<p><strong>Código 6.</strong> producir figura de resultados esperados</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="co"># valores de interés</span></span>
<span id="cb61-2"><a href="#cb61-2"></a>lo_ach <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb61-3"><a href="#cb61-3"></a>hi_ach <span class="ot">&lt;-</span>  <span class="dv">2</span></span>
<span id="cb61-4"><a href="#cb61-4"></a>lo_ses <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb61-5"><a href="#cb61-5"></a>hi_ses <span class="ot">&lt;-</span>  <span class="dv">2</span></span>
<span id="cb61-6"><a href="#cb61-6"></a></span>
<span id="cb61-7"><a href="#cb61-7"></a><span class="co"># coeficientes en logits del modelo</span></span>
<span id="cb61-8"><a href="#cb61-8"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">3.174</span></span>
<span id="cb61-9"><a href="#cb61-9"></a>b1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">1.174</span></span>
<span id="cb61-10"><a href="#cb61-10"></a>b2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.857</span></span>
<span id="cb61-11"><a href="#cb61-11"></a>b3 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.209</span></span>
<span id="cb61-12"><a href="#cb61-12"></a></span>
<span id="cb61-13"><a href="#cb61-13"></a><span class="co"># logits esperados a cada conjunto de valores de interés</span></span>
<span id="cb61-14"><a href="#cb61-14"></a>e_logit_1 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(lo_ach) <span class="sc">+</span> b2<span class="sc">*</span>(lo_ses) <span class="sc">+</span> b3<span class="sc">*</span>(lo_ach<span class="sc">*</span>lo_ses)</span>
<span id="cb61-15"><a href="#cb61-15"></a>e_logit_2 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(lo_ach) <span class="sc">+</span> b2<span class="sc">*</span>(hi_ses) <span class="sc">+</span> b3<span class="sc">*</span>(lo_ach<span class="sc">*</span>hi_ses)</span>
<span id="cb61-16"><a href="#cb61-16"></a>e_logit_3 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(hi_ach) <span class="sc">+</span> b2<span class="sc">*</span>(lo_ses) <span class="sc">+</span> b3<span class="sc">*</span>(hi_ach<span class="sc">*</span>lo_ses)</span>
<span id="cb61-17"><a href="#cb61-17"></a>e_logit_4 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(hi_ach) <span class="sc">+</span> b2<span class="sc">*</span>(hi_ses) <span class="sc">+</span> b3<span class="sc">*</span>(hi_ach<span class="sc">*</span>hi_ses)</span>
<span id="cb61-18"><a href="#cb61-18"></a></span>
<span id="cb61-19"><a href="#cb61-19"></a></span>
<span id="cb61-20"><a href="#cb61-20"></a><span class="co"># creamos tabla básica con los logits esperados</span></span>
<span id="cb61-21"><a href="#cb61-21"></a>data_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(     </span>
<span id="cb61-22"><a href="#cb61-22"></a><span class="at">x_var =</span> <span class="fu">c</span>(<span class="st">'Bajo NSE (-2 DS)'</span>,</span>
<span id="cb61-23"><a href="#cb61-23"></a>          <span class="st">'Alto NSE (+2 DS)'</span>,</span>
<span id="cb61-24"><a href="#cb61-24"></a>          <span class="st">'Bajo NSE (-2 DS)'</span>,</span>
<span id="cb61-25"><a href="#cb61-25"></a>          <span class="st">'Alto NSE (+2 DS)'</span>),       </span>
<span id="cb61-26"><a href="#cb61-26"></a><span class="at">y_var =</span> <span class="fu">c</span>(e_logit_1, e_logit_2, e_logit_3, e_logit_4),</span>
<span id="cb61-27"><a href="#cb61-27"></a><span class="at">group =</span> <span class="fu">c</span>(<span class="st">'Bajo Logro Académico (-2 SD)'</span>, </span>
<span id="cb61-28"><a href="#cb61-28"></a>          <span class="st">'Bajo Logro Académico (-2 SD)'</span>, </span>
<span id="cb61-29"><a href="#cb61-29"></a>          <span class="st">'Alto Logro Académico (+2 SD)'</span>,</span>
<span id="cb61-30"><a href="#cb61-30"></a>          <span class="st">'Alto Logro Académico (+2 SD)'</span>)</span>
<span id="cb61-31"><a href="#cb61-31"></a>)                                                     </span>
<span id="cb61-32"><a href="#cb61-32"></a></span>
<span id="cb61-33"><a href="#cb61-33"></a><span class="co"># reordenamos a los valores del factor ses</span></span>
<span id="cb61-34"><a href="#cb61-34"></a>data_plot_figure_1 <span class="ot">&lt;-</span> data_plot <span class="sc">%&gt;%</span>                           </span>
<span id="cb61-35"><a href="#cb61-35"></a><span class="fu">mutate</span>(<span class="at">ses_grp =</span> <span class="fu">as.factor</span>(x_var)) <span class="sc">%&gt;%</span>                        </span>
<span id="cb61-36"><a href="#cb61-36"></a><span class="fu">mutate</span>(<span class="at">ses_grp =</span>                                              </span>
<span id="cb61-37"><a href="#cb61-37"></a>  forcats<span class="sc">::</span><span class="fu">fct_relevel</span>(ses_grp,</span>
<span id="cb61-38"><a href="#cb61-38"></a>    <span class="fu">c</span>(<span class="st">'Bajo NSE (-2 DS)'</span>, <span class="st">'Alto NSE (+2 DS)'</span>)</span>
<span id="cb61-39"><a href="#cb61-39"></a>    )) <span class="sc">%&gt;%</span>                                                    </span>
<span id="cb61-40"><a href="#cb61-40"></a><span class="fu">mutate</span>(<span class="at">ach_grp =</span> <span class="fu">as.factor</span>(group)) <span class="sc">%&gt;%</span>                        </span>
<span id="cb61-41"><a href="#cb61-41"></a><span class="fu">mutate</span>(<span class="at">ach_grp =</span>                                              </span>
<span id="cb61-42"><a href="#cb61-42"></a>  forcats<span class="sc">::</span><span class="fu">fct_relevel</span>(ach_grp,</span>
<span id="cb61-43"><a href="#cb61-43"></a>    <span class="fu">c</span>(<span class="st">'Bajo Logro Académico (-2 SD)'</span>, </span>
<span id="cb61-44"><a href="#cb61-44"></a>      <span class="st">'Alto Logro Académico (+2 SD)'</span>)</span>
<span id="cb61-45"><a href="#cb61-45"></a>    )) <span class="sc">%&gt;%</span></span>
<span id="cb61-46"><a href="#cb61-46"></a><span class="fu">mutate</span>(<span class="at">expected_prob =</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>(<span class="fu">exp</span>(<span class="sc">-</span>y_var))))                   </span>
<span id="cb61-47"><a href="#cb61-47"></a></span>
<span id="cb61-48"><a href="#cb61-48"></a><span class="co"># creamos la figura 1</span></span>
<span id="cb61-49"><a href="#cb61-49"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-50"><a href="#cb61-50"></a>figure_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_plot_figure_1,  </span>
<span id="cb61-51"><a href="#cb61-51"></a>  <span class="fu">aes</span>(                                  </span>
<span id="cb61-52"><a href="#cb61-52"></a>    <span class="at">x =</span> ses_grp,                        </span>
<span id="cb61-53"><a href="#cb61-53"></a>    <span class="at">y =</span> expected_prob,                  </span>
<span id="cb61-54"><a href="#cb61-54"></a>    <span class="at">group =</span> ach_grp,                    </span>
<span id="cb61-55"><a href="#cb61-55"></a>    <span class="at">color =</span> ach_grp,                    </span>
<span id="cb61-56"><a href="#cb61-56"></a>    <span class="at">shape =</span> ach_grp                     </span>
<span id="cb61-57"><a href="#cb61-57"></a>    )) <span class="sc">+</span>                                </span>
<span id="cb61-58"><a href="#cb61-58"></a><span class="fu">geom_line</span>() <span class="sc">+</span>                           </span>
<span id="cb61-59"><a href="#cb61-59"></a><span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span>                    </span>
<span id="cb61-60"><a href="#cb61-60"></a><span class="fu">scale_color_manual</span>(                     </span>
<span id="cb61-61"><a href="#cb61-61"></a>  <span class="at">values =</span> <span class="fu">c</span>(                           </span>
<span id="cb61-62"><a href="#cb61-62"></a>    <span class="st">'Alto Logro Académico (+2 SD)'</span> <span class="ot">=</span> <span class="st">'red'</span>,                 </span>
<span id="cb61-63"><a href="#cb61-63"></a>    <span class="st">'Bajo Logro Académico (-2 SD)'</span> <span class="ot">=</span> <span class="st">'black'</span>                 </span>
<span id="cb61-64"><a href="#cb61-64"></a>    )) <span class="sc">+</span>                                </span>
<span id="cb61-65"><a href="#cb61-65"></a><span class="fu">scale_shape_manual</span>(                     </span>
<span id="cb61-66"><a href="#cb61-66"></a>  <span class="at">values =</span> <span class="fu">c</span>(                           </span>
<span id="cb61-67"><a href="#cb61-67"></a>    <span class="st">'Alto Logro Académico (+2 SD)'</span> <span class="ot">=</span> <span class="dv">19</span>,                    </span>
<span id="cb61-68"><a href="#cb61-68"></a>    <span class="st">'Bajo Logro Académico (-2 SD)'</span> <span class="ot">=</span> <span class="dv">15</span>                      </span>
<span id="cb61-69"><a href="#cb61-69"></a>    )) <span class="sc">+</span>                                </span>
<span id="cb61-70"><a href="#cb61-70"></a><span class="fu">xlab</span>(<span class="st">'Nivel socioeconómico de las familias (puntaje z)'</span>) <span class="sc">+</span> </span>
<span id="cb61-71"><a href="#cb61-71"></a><span class="fu">scale_y_continuous</span>(                     </span>
<span id="cb61-72"><a href="#cb61-72"></a>  <span class="at">name =</span> <span class="st">'Probabilidad de deserción escolar'</span>, </span>
<span id="cb61-73"><a href="#cb61-73"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,.<span class="dv">1</span>),                 </span>
<span id="cb61-74"><a href="#cb61-74"></a>  <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">6</span>)                      </span>
<span id="cb61-75"><a href="#cb61-75"></a>  ) <span class="sc">+</span>                                    </span>
<span id="cb61-76"><a href="#cb61-76"></a><span class="fu">theme_bw</span>() <span class="sc">+</span>                             </span>
<span id="cb61-77"><a href="#cb61-77"></a><span class="fu">theme</span>(                                   </span>
<span id="cb61-78"><a href="#cb61-78"></a>  <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),        </span>
<span id="cb61-79"><a href="#cb61-79"></a>  <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb61-80"><a href="#cb61-80"></a>  <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb61-81"><a href="#cb61-81"></a>  <span class="at">panel.grid.major.y =</span>                              </span>
<span id="cb61-82"><a href="#cb61-82"></a>  <span class="fu">element_line</span>(<span class="at">linewidth =</span> .<span class="dv">25</span>, <span class="at">colour =</span> <span class="st">"grey70"</span>)  </span>
<span id="cb61-83"><a href="#cb61-83"></a>  ) <span class="sc">+</span></span>
<span id="cb61-84"><a href="#cb61-84"></a><span class="fu">ggtitle</span>(</span>
<span id="cb61-85"><a href="#cb61-85"></a>  <span class="st">'Figura 1: Probabilidades de deserción escolar condicionales a valores ± 2 DS para NSE y Logro académico'</span>)                                                 </span>
<span id="cb61-86"><a href="#cb61-86"></a></span>
<span id="cb61-87"><a href="#cb61-87"></a></span>
<span id="cb61-88"><a href="#cb61-88"></a>figure_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="logit_results_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="descripcion-de-resultados" class="level1"><h1>7. Descripcion de resultados</h1>
<p>Usualmente, la estructura de descripcion de resultados de un modelo lineal generalizado posee los siguientes componentes:</p>
<ul>
<li>Un párrafo con la descripción del ajuste del modelo.
<ul>
<li>Se emplean estrategias de comparación de modelos entre sí para evaluar el ajuste global del modelo, mediante Likelihood ratio test.</li>
<li>Se pueden emplear indicadores de varianza explicada (e.g., McFadden <span class="math inline">\(R^2\)</span>)</li>
<li>Se emplean tambien indicadores de precision de clasificación (i.e., count <span class="math inline">\(R^2\)</span>)</li>
</ul>
</li>
<li>Párrafos describiendo los resultados encontrados, segun las preguntas de investigación.
<ul>
<li>En general, los autores se centran los coeficientes que abordan sus preguntas de investigación.</li>
</ul>
</li>
<li>Se emplean tablas y gráficos para ilustrar los resultados
<ul>
<li>Los autores emplean en general al menos una tabla, y a veces figuras de resultados para facilitar la lectura de sus resultados.</li>
</ul>
</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Nota">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para que resultados descritos tengan sentido esbozamos una introducción breve. Esta sigue la estructura de tres partes recomendada por Booth et al (2016). Esta introducción requiere incluir tres partes: una descripción del tópico, una descripción del problema, y una descripción de la propuesta. Emplearemos este formato de introducción de modo que los resultados descritos sean lo más realista posible, ya que es el problema de investigación lo que condiciona a como son descritos los resultados encontrados.</p>
</div>
</div>
<section id="introducción-1" class="level2"><h2 class="anchored" data-anchor-id="introducción-1">Introducción</h2>
<ul>
<li><p>El dropout escolar es un problema reconocido en términos de política pública para los paises. Es uno de los riesgo negativos más grandes en salud pública (Freudenberg et al., 2007), así como un conocido factor detrimental para la empleabilidad futura de las persoas (Solga, 2002). Este fenómeno interrumpe el proceso educativo del cual participan los estudiantes, y mientras más temprano ocurra, mayores son las consecuenci</p></li>
<li><p>Los indicadores de riesgo con mayor cobertura en el estudio de dropout escolar, es el desempeño académico de los estudiantes, y el nivel socioeconómico de las familias de los estudiantes. Sin embargo, una pregunta que posee menor cobertura en la literatura son los posibles efectos de interacción de estos factores. Esta pregunta es común que no sea abordada en estudios previos, debido a la falta de poder estadístico (e.g., Sommet, 2023). Mientras la evaluación de relaciones entre variables requiere de muestras de unos 100 casos, para la adecuada evaluación relaciones condicionales se puede requerir de muestras de hasta 16 veces el tamaño anterior (Gellman, 2008).</p></li>
<li><p>El presente estudio se sirve de una muestra de datos nacional de gran tamaño (n = 16610) para estudiar el rol del nivel socioeconómico de los estudiantes sobre el dropout escolar. En particular, queremos saber si este factor es un factor de riesgo para todos los estudiantes, y/o si es un factor de riesgo que posee mayores consecuencias para estudiantes de menor desempeño académico.</p></li>
</ul></section><section id="método" class="level2"><h2 class="anchored" data-anchor-id="método">Método</h2>
<ul>
<li>[aqui iría la descripción de la muestra, las variables empleadas, y el tipo de modelo de estadístico empleado para producir los resultados empleados en la argumentación del artículo].</li>
</ul></section><section id="texto_resultados" class="level2"><h2 class="anchored" data-anchor-id="texto_resultados">Resultados</h2>
<p><em><strong>Ajuste global</strong></em>. El modelo final, en contraste al modelo nulo presenta un mejor ajuste (LRT(3) = 1921.72, p &lt; .001). Este modelo reduce el error del modelo nulo en cerca de 19% (McFadden Adj <span class="math inline">\(R^2\)</span> = 0.19). El modelo clasifica de forma adecuada a 91% de las observaciones (count <span class="math inline">\(R^2\)</span> = .01). Con estos resultados concluimos, que en forma global, el desempeño académico de los estudiantes en octavo grado, y los antecedentes socioeconómicos de las familias, son relevantes para entender la tasa de deserción escolar de los estudiantes secundarios.</p>
<p><em><strong>Resultados</strong></em>. En terminos generales, se observa que entre los estudiantes incluidos en el estudios, se observa una tasa de deserción escolar de 8.89%.</p>
<p>Con los resultados obtenidos del modelo ajustado podemos indicar que los estudiantes con mayores logros académicos al inicio de la ventana de observación presentan menores chances de interrumpir su trayectoria escolar (b = -3.17 (0.05), p &lt; .001, OR = .31). En términos relativos, esto indica que los estudiantes con 1 desviación estandar mayor de desempeño académico, tienen 3 veces más chances de concluir sus estudios de secundaria, que el resto de sus pares (1/OR = 3.23).</p>
<p>Por su parte, el nivel socioeconómico de las familias de los estudiantes tambien presenta una relación negativa con la deserción escolar (b = -1.17 (0.05), p &lt; .001, OR = .42; 1/OR = 2.36). Estudiantes de familias con mayor nivel socioeconómico presentan mayores chances de completar sus estudios escolares. En terminos relativos, estudiantes a una desviación estándar de mayor nivel socioeconómico, presentan más del doble de chances de completar sus estudios escolares (1/OR = 2.36).</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Código que genera a la Tabla 1 de resultados</summary><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a><span class="co"># metodo 4: broom::tidy() y edición de campus</span></span>
<span id="cb62-2"><a href="#cb62-2"></a></span>
<span id="cb62-3"><a href="#cb62-3"></a><span class="do">## función para decinir 2 decimales</span></span>
<span id="cb62-4"><a href="#cb62-4"></a>decimales <span class="ot">&lt;-</span> <span class="cf">function</span> (x, k) {</span>
<span id="cb62-5"><a href="#cb62-5"></a>    <span class="fu">format</span>(<span class="fu">round</span>(x, k), <span class="at">nsmall =</span> k)</span>
<span id="cb62-6"><a href="#cb62-6"></a>}</span>
<span id="cb62-7"><a href="#cb62-7"></a></span>
<span id="cb62-8"><a href="#cb62-8"></a></span>
<span id="cb62-9"><a href="#cb62-9"></a><span class="do">## tabla con estimados</span></span>
<span id="cb62-10"><a href="#cb62-10"></a>tabla_1 <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(m04) <span class="sc">%&gt;%</span></span>
<span id="cb62-11"><a href="#cb62-11"></a><span class="fu">mutate</span>(<span class="at">text =</span> <span class="fu">case_when</span>(</span>
<span id="cb62-12"><a href="#cb62-12"></a>term <span class="sc">==</span> <span class="st">'(Intercept)'</span> <span class="sc">~</span> <span class="st">'intercepto'</span>,</span>
<span id="cb62-13"><a href="#cb62-13"></a>term <span class="sc">==</span> <span class="st">'zach'</span>        <span class="sc">~</span> <span class="st">'logro académico (puntaje z)'</span>,</span>
<span id="cb62-14"><a href="#cb62-14"></a>term <span class="sc">==</span> <span class="st">'zses'</span>        <span class="sc">~</span> <span class="st">'nivel socioeconómico (puntaje z)'</span>,</span>
<span id="cb62-15"><a href="#cb62-15"></a>term <span class="sc">==</span> <span class="st">'int'</span>         <span class="sc">~</span> <span class="st">'interacción'</span></span>
<span id="cb62-16"><a href="#cb62-16"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-17"><a href="#cb62-17"></a><span class="fu">mutate</span>(<span class="at">e  =</span> <span class="fu">decimales</span>(estimate, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-18"><a href="#cb62-18"></a><span class="fu">mutate</span>(<span class="at">se =</span> <span class="fu">paste0</span>(<span class="st">'('</span>, <span class="fu">decimales</span>(std.error, <span class="dv">2</span>), <span class="st">')'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-19"><a href="#cb62-19"></a><span class="fu">mutate</span>(<span class="at">star =</span> <span class="fu">case_when</span>(</span>
<span id="cb62-20"><a href="#cb62-20"></a>p.value <span class="sc">&lt;</span>  .<span class="dv">001</span> <span class="sc">~</span> <span class="st">'***'</span>,</span>
<span id="cb62-21"><a href="#cb62-21"></a>p.value <span class="sc">&lt;</span>  .<span class="dv">01</span>  <span class="sc">~</span> <span class="st">'** '</span>,</span>
<span id="cb62-22"><a href="#cb62-22"></a>p.value <span class="sc">&lt;</span>  .<span class="dv">05</span>  <span class="sc">~</span> <span class="st">'*  '</span>,</span>
<span id="cb62-23"><a href="#cb62-23"></a>p.value <span class="sc">&gt;=</span> .<span class="dv">05</span>  <span class="sc">~</span> <span class="st">'   '</span></span>
<span id="cb62-24"><a href="#cb62-24"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-25"><a href="#cb62-25"></a><span class="fu">mutate</span>(<span class="at">odds_ratio =</span> <span class="fu">decimales</span>(<span class="fu">exp</span>(estimate),<span class="dv">2</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb62-26"><a href="#cb62-26"></a><span class="fu">mutate</span>(<span class="at">reverse_odds_ratio =</span> <span class="fu">decimales</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">exp</span>(estimate),<span class="dv">2</span>))  <span class="sc">%&gt;%</span></span>
<span id="cb62-27"><a href="#cb62-27"></a><span class="fu">mutate</span>(<span class="at">odds_ratio =</span> <span class="fu">case_when</span>(</span>
<span id="cb62-28"><a href="#cb62-28"></a>text <span class="sc">==</span> <span class="st">'intercepto'</span> <span class="sc">~</span> <span class="st">''</span>,</span>
<span id="cb62-29"><a href="#cb62-29"></a>text <span class="sc">!=</span> <span class="st">'intercepto'</span> <span class="sc">~</span> odds_ratio</span>
<span id="cb62-30"><a href="#cb62-30"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-31"><a href="#cb62-31"></a><span class="fu">mutate</span>(<span class="at">reverse_odds_ratio =</span> <span class="fu">case_when</span>(</span>
<span id="cb62-32"><a href="#cb62-32"></a>text <span class="sc">==</span> <span class="st">'intercepto'</span> <span class="sc">~</span> <span class="st">''</span>,</span>
<span id="cb62-33"><a href="#cb62-33"></a>text <span class="sc">!=</span> <span class="st">'intercepto'</span> <span class="sc">~</span> reverse_odds_ratio</span>
<span id="cb62-34"><a href="#cb62-34"></a>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-35"><a href="#cb62-35"></a>dplyr<span class="sc">::</span><span class="fu">select</span>(text, e, se, star, odds_ratio, reverse_odds_ratio)</span>
<span id="cb62-36"><a href="#cb62-36"></a></span>
<span id="cb62-37"><a href="#cb62-37"></a>tabla_1 <span class="sc">%&gt;%</span></span>
<span id="cb62-38"><a href="#cb62-38"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(., <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">caption =</span> <span class="st">'Tabla 1: resultados de regresión logística sobre el evento de deserción escolar'</span>)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Tabla 1: resultados de regresión logística sobre el evento de deserción escolar</caption>
<colgroup>
<col style="width: 40%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">text</th>
<th style="text-align: left;">e</th>
<th style="text-align: left;">se</th>
<th style="text-align: left;">star</th>
<th style="text-align: left;">odds_ratio</th>
<th style="text-align: left;">reverse_odds_ratio</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercepto</td>
<td style="text-align: left;">-3.17</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">logro académico (puntaje z)</td>
<td style="text-align: left;">-1.17</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;">0.31</td>
<td style="text-align: left;">3.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nivel socioeconómico (puntaje z)</td>
<td style="text-align: left;">-0.86</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">2.36</td>
</tr>
<tr class="even">
<td style="text-align: left;">interacción</td>
<td style="text-align: left;">-0.21</td>
<td style="text-align: left;">(0.05)</td>
<td style="text-align: left;">***</td>
<td style="text-align: left;">0.81</td>
<td style="text-align: left;">1.23</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Finalmente, observamos que estos dos factores, desempeño académico en 8vo grado, y nivel socioeconómico de las familias, son factores que interactúan entre sí (b = -0.21 (0.05), p &lt; .001). Para ilustrar la dirección de estos resultados, vamos a producir probabilidades condicionales a -2 y 2 desviaciones estándar por sobre el promedio para desempeño académico, y nivel socioeconómico de las familias, e ilustraremos estos resultados con la Figura 1.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold"><summary>Código que genera a la Figura 1 para ilustrar la Interacción</summary><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a><span class="co"># valores de interés</span></span>
<span id="cb63-2"><a href="#cb63-2"></a>lo_ach <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb63-3"><a href="#cb63-3"></a>hi_ach <span class="ot">&lt;-</span>  <span class="dv">2</span></span>
<span id="cb63-4"><a href="#cb63-4"></a>lo_ses <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span></span>
<span id="cb63-5"><a href="#cb63-5"></a>hi_ses <span class="ot">&lt;-</span>  <span class="dv">2</span></span>
<span id="cb63-6"><a href="#cb63-6"></a></span>
<span id="cb63-7"><a href="#cb63-7"></a><span class="co"># coeficientes en logits del modelo</span></span>
<span id="cb63-8"><a href="#cb63-8"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">3.174</span></span>
<span id="cb63-9"><a href="#cb63-9"></a>b1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">1.174</span></span>
<span id="cb63-10"><a href="#cb63-10"></a>b2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.857</span></span>
<span id="cb63-11"><a href="#cb63-11"></a>b3 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.209</span></span>
<span id="cb63-12"><a href="#cb63-12"></a></span>
<span id="cb63-13"><a href="#cb63-13"></a><span class="co"># logits esperados a cada conjunto de valores de interés</span></span>
<span id="cb63-14"><a href="#cb63-14"></a>e_logit_1 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(lo_ach) <span class="sc">+</span> b2<span class="sc">*</span>(lo_ses) <span class="sc">+</span> b3<span class="sc">*</span>(lo_ach<span class="sc">*</span>lo_ses)</span>
<span id="cb63-15"><a href="#cb63-15"></a>e_logit_2 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(lo_ach) <span class="sc">+</span> b2<span class="sc">*</span>(hi_ses) <span class="sc">+</span> b3<span class="sc">*</span>(lo_ach<span class="sc">*</span>hi_ses)</span>
<span id="cb63-16"><a href="#cb63-16"></a>e_logit_3 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(hi_ach) <span class="sc">+</span> b2<span class="sc">*</span>(lo_ses) <span class="sc">+</span> b3<span class="sc">*</span>(hi_ach<span class="sc">*</span>lo_ses)</span>
<span id="cb63-17"><a href="#cb63-17"></a>e_logit_4 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>(hi_ach) <span class="sc">+</span> b2<span class="sc">*</span>(hi_ses) <span class="sc">+</span> b3<span class="sc">*</span>(hi_ach<span class="sc">*</span>hi_ses)</span>
<span id="cb63-18"><a href="#cb63-18"></a></span>
<span id="cb63-19"><a href="#cb63-19"></a></span>
<span id="cb63-20"><a href="#cb63-20"></a><span class="co"># creamos tabla básica con los logits esperados</span></span>
<span id="cb63-21"><a href="#cb63-21"></a>data_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(     </span>
<span id="cb63-22"><a href="#cb63-22"></a><span class="at">x_var =</span> <span class="fu">c</span>(<span class="st">'Bajo NSE (-2 DS)'</span>,</span>
<span id="cb63-23"><a href="#cb63-23"></a>          <span class="st">'Alto NSE (+2 DS)'</span>,</span>
<span id="cb63-24"><a href="#cb63-24"></a>          <span class="st">'Bajo NSE (-2 DS)'</span>,</span>
<span id="cb63-25"><a href="#cb63-25"></a>          <span class="st">'Alto NSE (+2 DS)'</span>),       </span>
<span id="cb63-26"><a href="#cb63-26"></a><span class="at">y_var =</span> <span class="fu">c</span>(e_logit_1, e_logit_2, e_logit_3, e_logit_4),</span>
<span id="cb63-27"><a href="#cb63-27"></a><span class="at">group =</span> <span class="fu">c</span>(<span class="st">'Bajo Logro Académico (-2 SD)'</span>, </span>
<span id="cb63-28"><a href="#cb63-28"></a>          <span class="st">'Bajo Logro Académico (-2 SD)'</span>, </span>
<span id="cb63-29"><a href="#cb63-29"></a>          <span class="st">'Alto Logro Académico (+2 SD)'</span>,</span>
<span id="cb63-30"><a href="#cb63-30"></a>          <span class="st">'Alto Logro Académico (+2 SD)'</span>)</span>
<span id="cb63-31"><a href="#cb63-31"></a>)                                                     </span>
<span id="cb63-32"><a href="#cb63-32"></a></span>
<span id="cb63-33"><a href="#cb63-33"></a><span class="co"># reordenamos a los valores del factor ses</span></span>
<span id="cb63-34"><a href="#cb63-34"></a>data_plot_figure_1 <span class="ot">&lt;-</span> data_plot <span class="sc">%&gt;%</span>                           </span>
<span id="cb63-35"><a href="#cb63-35"></a><span class="fu">mutate</span>(<span class="at">ses_grp =</span> <span class="fu">as.factor</span>(x_var)) <span class="sc">%&gt;%</span>                        </span>
<span id="cb63-36"><a href="#cb63-36"></a><span class="fu">mutate</span>(<span class="at">ses_grp =</span>                                              </span>
<span id="cb63-37"><a href="#cb63-37"></a>  forcats<span class="sc">::</span><span class="fu">fct_relevel</span>(ses_grp,</span>
<span id="cb63-38"><a href="#cb63-38"></a>    <span class="fu">c</span>(<span class="st">'Bajo NSE (-2 DS)'</span>, <span class="st">'Alto NSE (+2 DS)'</span>)</span>
<span id="cb63-39"><a href="#cb63-39"></a>    )) <span class="sc">%&gt;%</span>                                                    </span>
<span id="cb63-40"><a href="#cb63-40"></a><span class="fu">mutate</span>(<span class="at">ach_grp =</span> <span class="fu">as.factor</span>(group)) <span class="sc">%&gt;%</span>                        </span>
<span id="cb63-41"><a href="#cb63-41"></a><span class="fu">mutate</span>(<span class="at">ach_grp =</span>                                              </span>
<span id="cb63-42"><a href="#cb63-42"></a>  forcats<span class="sc">::</span><span class="fu">fct_relevel</span>(ach_grp,</span>
<span id="cb63-43"><a href="#cb63-43"></a>    <span class="fu">c</span>(<span class="st">'Bajo Logro Académico (-2 SD)'</span>, </span>
<span id="cb63-44"><a href="#cb63-44"></a>      <span class="st">'Alto Logro Académico (+2 SD)'</span>)</span>
<span id="cb63-45"><a href="#cb63-45"></a>    )) <span class="sc">%&gt;%</span></span>
<span id="cb63-46"><a href="#cb63-46"></a><span class="fu">mutate</span>(<span class="at">expected_prob =</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>(<span class="fu">exp</span>(<span class="sc">-</span>y_var))))                   </span>
<span id="cb63-47"><a href="#cb63-47"></a></span>
<span id="cb63-48"><a href="#cb63-48"></a><span class="co"># creamos la figura 1</span></span>
<span id="cb63-49"><a href="#cb63-49"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb63-50"><a href="#cb63-50"></a>figure_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_plot_figure_1,  </span>
<span id="cb63-51"><a href="#cb63-51"></a>  <span class="fu">aes</span>(                                  </span>
<span id="cb63-52"><a href="#cb63-52"></a>    <span class="at">x =</span> ses_grp,                        </span>
<span id="cb63-53"><a href="#cb63-53"></a>    <span class="at">y =</span> expected_prob,                  </span>
<span id="cb63-54"><a href="#cb63-54"></a>    <span class="at">group =</span> ach_grp,                    </span>
<span id="cb63-55"><a href="#cb63-55"></a>    <span class="at">color =</span> ach_grp,                    </span>
<span id="cb63-56"><a href="#cb63-56"></a>    <span class="at">shape =</span> ach_grp                     </span>
<span id="cb63-57"><a href="#cb63-57"></a>    )) <span class="sc">+</span>                                </span>
<span id="cb63-58"><a href="#cb63-58"></a><span class="fu">geom_line</span>() <span class="sc">+</span>                           </span>
<span id="cb63-59"><a href="#cb63-59"></a><span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span>                    </span>
<span id="cb63-60"><a href="#cb63-60"></a><span class="fu">scale_color_manual</span>(                     </span>
<span id="cb63-61"><a href="#cb63-61"></a>  <span class="at">values =</span> <span class="fu">c</span>(                           </span>
<span id="cb63-62"><a href="#cb63-62"></a>    <span class="st">'Alto Logro Académico (+2 SD)'</span> <span class="ot">=</span> <span class="st">'red'</span>,                 </span>
<span id="cb63-63"><a href="#cb63-63"></a>    <span class="st">'Bajo Logro Académico (-2 SD)'</span> <span class="ot">=</span> <span class="st">'black'</span>                 </span>
<span id="cb63-64"><a href="#cb63-64"></a>    )) <span class="sc">+</span>                                </span>
<span id="cb63-65"><a href="#cb63-65"></a><span class="fu">scale_shape_manual</span>(                     </span>
<span id="cb63-66"><a href="#cb63-66"></a>  <span class="at">values =</span> <span class="fu">c</span>(                           </span>
<span id="cb63-67"><a href="#cb63-67"></a>    <span class="st">'Alto Logro Académico (+2 SD)'</span> <span class="ot">=</span> <span class="dv">19</span>,                    </span>
<span id="cb63-68"><a href="#cb63-68"></a>    <span class="st">'Bajo Logro Académico (-2 SD)'</span> <span class="ot">=</span> <span class="dv">15</span>                      </span>
<span id="cb63-69"><a href="#cb63-69"></a>    )) <span class="sc">+</span>                                </span>
<span id="cb63-70"><a href="#cb63-70"></a><span class="fu">xlab</span>(<span class="st">'Nivel socioeconómico de las familias (puntaje z)'</span>) <span class="sc">+</span> </span>
<span id="cb63-71"><a href="#cb63-71"></a><span class="fu">scale_y_continuous</span>(                     </span>
<span id="cb63-72"><a href="#cb63-72"></a>  <span class="at">name =</span> <span class="st">'Probabilidad de deserción escolar'</span>, </span>
<span id="cb63-73"><a href="#cb63-73"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,.<span class="dv">1</span>),                 </span>
<span id="cb63-74"><a href="#cb63-74"></a>  <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">6</span>)                      </span>
<span id="cb63-75"><a href="#cb63-75"></a>  ) <span class="sc">+</span>                                    </span>
<span id="cb63-76"><a href="#cb63-76"></a><span class="fu">theme_bw</span>() <span class="sc">+</span>                             </span>
<span id="cb63-77"><a href="#cb63-77"></a><span class="fu">theme</span>(                                   </span>
<span id="cb63-78"><a href="#cb63-78"></a>  <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),        </span>
<span id="cb63-79"><a href="#cb63-79"></a>  <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb63-80"><a href="#cb63-80"></a>  <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb63-81"><a href="#cb63-81"></a>  <span class="at">panel.grid.major.y =</span>                              </span>
<span id="cb63-82"><a href="#cb63-82"></a>  <span class="fu">element_line</span>(<span class="at">linewidth =</span> .<span class="dv">25</span>, <span class="at">colour =</span> <span class="st">"grey70"</span>)  </span>
<span id="cb63-83"><a href="#cb63-83"></a>  ) <span class="sc">+</span></span>
<span id="cb63-84"><a href="#cb63-84"></a><span class="fu">ggtitle</span>(</span>
<span id="cb63-85"><a href="#cb63-85"></a>  <span class="st">'Figura 1: Probabilidades de deserción escolar condicionales a valores ± 2 DS para NSE y Logro académico'</span>)                                                 </span>
<span id="cb63-86"><a href="#cb63-86"></a></span>
<span id="cb63-87"><a href="#cb63-87"></a></span>
<span id="cb63-88"><a href="#cb63-88"></a>figure_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="logit_results_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A medida que aumentan los valores de nivel socioeconómico de las familias, la distancia de las probabilidades condicionales de deserción escolar, disminuyen entre los estudiantes de bajo y alto desempeño escolar. Finalmente, el nivel socioeconómico de las familias <em>acelera</em> la relación que observamos del desempeño académico a la deserción escolar. De tal forma que los estudiantes de familias de menor nivel socieconómico, presentan mayores chances de deserción escolar, escolar entre los estuddiantes de menores niveles de logro académico, en contraste a sus pares que presentan mayor logro académico.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Nota">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>En el siguiente <a href="https://www.dropbox.com/scl/fi/w1tpynr8qt5aj51n4y4v9/tabla_1_resultados.xlsx?rlkey=8o1m3hy91wpyfhyxp71i8sdqz&amp;dl=1">link</a>, se puede bajar la tabla de resultados generadas en excel, y también en editada en un <a href="https://www.dropbox.com/scl/fi/7ibgh6gcjpj2luagohsde/tabla_1_resultados_apa_format.xlsx?rlkey=9o5kmxtowqa9n0oxt9i11tgfg&amp;dl=1">formato tipo APA</a>.</p>
</div>
</div>
</section></section><section id="referencias" class="level1"><h1>Referencias</h1>
<p>Booth, W. C., Colomb, G. G., Williams, J. M., Bizup, J., &amp; FitzGerald, W. T. (2016). The Craft of Research (4th ed.). University of Chicago Press. https://doi.org/10.7208/chicago/9780226239873.001.0001</p>
<p>Dunn, P. K., &amp; Smyth, G. K. (2018). Generalized Linear Models With Examples in R. In Springer New York, NY. Springer New York. https://doi.org/10.1007/978-1-4419-0118-7</p>
<p>Harrell, F. E. (2015). Regression Modeling Strategies. Springer International Publishing. https://doi.org/10.1007/978-3-319-19425-7</p>
<p>Heiss, A. (2022). Marginalia: A guide to figuring out what the heck marginal effects, marginal slopes, average marginal effects, marginal effects at the mean, and all these other marginal things are (pp.&nbsp;1–56). https://doi.org/10.59350/40xaj-4e562</p>
<p>Hemmert, G. A. J., Schons, L. M., Wieseke, J., &amp; Schimmelpfennig, H. (2018). Log-likelihood-based Pseudo-R2 in Logistic Regression: Deriving Sample-sensitive Benchmarks. Sociological Methods and Research, 47(3), 507–531. https://doi.org/10.1177/0049124116638107</p>
<p>Huck, S. W. (2012). Bivariate, Multiple, and Logistic Regression. In Reading Statistics and Research (6th ed., pp.&nbsp;367–403). Pearson Education.</p>
<p>Klecka, W. (1980). Discriminant Analysis. SAGE Publications Inc.</p>
<p>Lüdecke, D., Ben-Shachar, M., Patil, I., Waggoner, P., &amp; Makowski, D. (2021). performance: An R Package for Assessment, Comparison and Testing of Statistical Models. Journal of Open Source Software, 6(60), 3139. https://doi.org/10.21105/joss.03139</p>
<p>Ma, Z., &amp; Redmond, R. L. (1995). Tau Coefficients for Accuracy Assessment of Classification of Remote Sensing Data. Photogrammetric Engineering and Remote Sensing, 61(4), 435–439.</p>
<p>Menard, S. (2000). Coefficients of determination for multiple logistic regression analysis. American Statistician, 54(1), 17–24. https://doi.org/10.1080/00031305.2000.10474502</p>
<p>Niu, L. (2020). A review of the application of logistic regression in educational research: common issues, implications, and suggestions. Educational Review, 72(1), 41–67. https://doi.org/10.1080/00131911.2018.1483892</p>
<p>O’Connell, A. A., &amp; Amico, K. R. (2019). Logistic Regression and Extensions. In The Reviewer’s Guide to Quantitative Methods in the Social Sciences (2nd ed., pp.&nbsp;214–234). Routledge. https://doi.org/10.4324/9781315755649-16</p>
<p>Osborne, J. W. (2012). Logits and tigers and bears , oh my! A brief look at the simple math of logistic regression and how it can improve dissemination of results. Practical Assessment, Research and Evaluation, 17(June 2012), 1–10.</p>
<p>Sommet, N., Weissman, D. L., Cheutin, N., &amp; Elliot, A. J. (2023). How Many Participants Do I Need to Test an Interaction? Conducting an Appropriate Power Analysis and Achieving Sufficient Power to Detect an Interaction. Advances in Methods and Practices in Psychological Science, 6(3). https://doi.org/10.1177/25152459231178728</p>
</section><section id="anexos" class="level1"><h1>Anexos</h1>
<section id="anexo-1-colinealidad" class="level2"><h2 class="anchored" data-anchor-id="anexo-1-colinealidad">Anexo 1: Colinealidad</h2>
<p>La librería <code>blorr</code> provee de una función directa para diagnosticas la posible colinealidad de las covariables. En general, se esperan valores menores a 4 en el indicador VIF (i.e., <em>variance inflation factor</em>). Para mayores detalles de como VIF puede afectar a los errores de un modelo ver la siguiente nota en <a href="https://stats.stackexchange.com/questions/342161/how-do-i-know-what-my-vif-limits-should-be-for-collinearity-should-be-when-doing">stackexchange</a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a>blorr<span class="sc">::</span><span class="fu">blr_vif_tol</span>(m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Variable Tolerance      VIF
1     zach 0.7296288 1.370560
2     zses 0.7447871 1.342666
3      int 0.9761323 1.024451</code></pre>
</div>
</div>
</section><section id="anexo-2-residuales" class="level2"><h2 class="anchored" data-anchor-id="anexo-2-residuales">Anexo 2: Residuales</h2>
<p>Existen diferentes tipos de residuales en el caso de la regresión logistica (ver Dunn, et al.&nbsp;(2018), p299). Uno de los más intuitivos son los residuales basados en devianzas, que se encuentran <em>unit deviance</em>, y son los que produce por defecto el paquete base de R (i.e., <code>residual(model)</code>), para el caso de modelo de regresion logística.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="co"># residuales basados en devianza</span></span>
<span id="cb66-2"><a href="#cb66-2"></a>blorr<span class="sc">::</span><span class="fu">blr_plot_deviance_residual</span>(m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="logit_results_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>De forma muy intuitiva, se pueden hacer dos cosas con los residuales. Lo primero es que es más conveniente que estos se distribuyan de forma similar a entre las observaciones. De caso contrario, uno puede sospechar que el modelo ajusta de mejor manera para algunas observaciones, en contraste a otras.</p>
<p>Harrel (2015) es de la opinión que el diagnóstico general de lo residuales de los modelos de regresión logística es menos util, que en el caso de la regresión lineal. Lo anterior, porque el modelo no posee una distribución esperada para los residuales (e.g., por ejemplo una distrivución normal). En terminos más generales la regresión logística no posee un modelo para los errores, como en el caso de la regresión lineal.</p>
<p>Por su parte Dunn et al.&nbsp;(2018, p228) muestra los residuales de la unidad de devianza (i.e., <em>unit deviance</em>), que es la escala que en se encuentran los residuales que produce por defecto, poseen una distribución cercana <span class="math inline">\(\chi^2\)</span>. Y estos valores debieran ser cercanos a 1; sin embargo si la prevancia de <span class="math inline">\(Pr(y=1)\)</span> es muy alta o muy baja (menor a .1, o mayor .9), las devianzas esperadas se <em>empinan</em> y pueden ser mayores a 1.</p>
<p>En el modelo ajustado, esto es precisamete lo que sucede, ya que estamos modelando una variable de respuesta donde se observa <span class="math inline">\(Pr(y=1) = .09\)</span>. En este caso observamos varios casos son residuales por sobre 1 entre los valores que presentan el evento.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1"></a><span class="co"># figura comparada</span></span>
<span id="cb67-2"><a href="#cb67-2"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb67-3"><a href="#cb67-3"></a>plot_1 <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">augment</span>(m04) <span class="sc">%&gt;%</span></span>
<span id="cb67-4"><a href="#cb67-4"></a>dplyr<span class="sc">::</span><span class="fu">filter</span>(drop <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb67-5"><a href="#cb67-5"></a><span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x=</span>.resid)) <span class="sc">+</span> </span>
<span id="cb67-6"><a href="#cb67-6"></a><span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb67-7"><a href="#cb67-7"></a><span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb67-8"><a href="#cb67-8"></a><span class="fu">theme</span>(                                   </span>
<span id="cb67-9"><a href="#cb67-9"></a>  <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),        </span>
<span id="cb67-10"><a href="#cb67-10"></a>  <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb67-11"><a href="#cb67-11"></a>  <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb67-12"><a href="#cb67-12"></a>  <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb67-13"><a href="#cb67-13"></a>  <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>()</span>
<span id="cb67-14"><a href="#cb67-14"></a>  )     <span class="sc">+</span></span>
<span id="cb67-15"><a href="#cb67-15"></a><span class="fu">xlab</span>(<span class="st">'Residuales (Deviance)'</span>)</span>
<span id="cb67-16"><a href="#cb67-16"></a></span>
<span id="cb67-17"><a href="#cb67-17"></a>plot_2 <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">augment</span>(m04) <span class="sc">%&gt;%</span></span>
<span id="cb67-18"><a href="#cb67-18"></a>dplyr<span class="sc">::</span><span class="fu">filter</span>(drop <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb67-19"><a href="#cb67-19"></a><span class="fu">ggplot</span>(., <span class="fu">aes</span>(<span class="at">x=</span>.resid)) <span class="sc">+</span> </span>
<span id="cb67-20"><a href="#cb67-20"></a><span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb67-21"><a href="#cb67-21"></a><span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb67-22"><a href="#cb67-22"></a><span class="fu">theme</span>(                                   </span>
<span id="cb67-23"><a href="#cb67-23"></a>  <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),        </span>
<span id="cb67-24"><a href="#cb67-24"></a>  <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb67-25"><a href="#cb67-25"></a>  <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb67-26"><a href="#cb67-26"></a>  <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),  </span>
<span id="cb67-27"><a href="#cb67-27"></a>  <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>()</span>
<span id="cb67-28"><a href="#cb67-28"></a>  )     <span class="sc">+</span></span>
<span id="cb67-29"><a href="#cb67-29"></a><span class="fu">xlab</span>(<span class="st">'Residuales (Deviance)'</span>)</span>
<span id="cb67-30"><a href="#cb67-30"></a></span>
<span id="cb67-31"><a href="#cb67-31"></a><span class="co"># reorganizar las figuras generadas</span></span>
<span id="cb67-32"><a href="#cb67-32"></a>plot_in_wide <span class="ot">&lt;-</span> cowplot<span class="sc">::</span><span class="fu">plot_grid</span>(</span>
<span id="cb67-33"><a href="#cb67-33"></a>    plot_1 <span class="sc">+</span> </span>
<span id="cb67-34"><a href="#cb67-34"></a>      <span class="fu">ggtitle</span>(<span class="st">'Residuales entre</span><span class="sc">\n</span><span class="st">observaciones que no presentan el evento'</span>) <span class="sc">+</span> </span>
<span id="cb67-35"><a href="#cb67-35"></a>      <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>),</span>
<span id="cb67-36"><a href="#cb67-36"></a>    plot_2 <span class="sc">+</span> </span>
<span id="cb67-37"><a href="#cb67-37"></a>      <span class="fu">ggtitle</span>(<span class="st">'Residuales entre</span><span class="sc">\n</span><span class="st">observaciones que sí presentan el evento'</span>) <span class="sc">+</span> </span>
<span id="cb67-38"><a href="#cb67-38"></a>      <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'none'</span>),</span>
<span id="cb67-39"><a href="#cb67-39"></a>    <span class="at">ncol=</span><span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span></span>
<span id="cb67-40"><a href="#cb67-40"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1"></a><span class="co"># mostrar a las figuras generadas</span></span>
<span id="cb69-2"><a href="#cb69-2"></a>plot_in_wide</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="logit_results_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="anexo-3-efectos-marginales-average-marginal-effects" class="level2"><h2 class="anchored" data-anchor-id="anexo-3-efectos-marginales-average-marginal-effects">Anexo 3: Efectos marginales (Average Marginal Effects)</h2>
<p>Como fuera visto en clase podemos obtener los <em>efectos marginales</em>, en particular los <em>average marginal effects</em>. Estos nos entregan el <em>cambio</em> esperado en escala de probabilidad, por sobre el promedio, para cada unidad sobre cada covariable del mdoelo. Sin embargo, en esta guía empleamos probabilidades condicionales esperadas a valores particulares para ilustrar los resultados esperados, siguiendo a Osborne (2012).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a><span class="co"># efectos marginales (average marginal effects)</span></span>
<span id="cb70-2"><a href="#cb70-2"></a>marginaleffects<span class="sc">::</span><span class="fu">avg_slopes</span>(m04)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Term Estimate Std. Error      z Pr(&gt;|z|)     S   2.5 %   97.5 %
 int   -0.0148    0.00367  -4.04   &lt;0.001  14.2 -0.0220 -0.00763
 zach  -0.0832    0.00401 -20.76   &lt;0.001 315.6 -0.0911 -0.07535
 zses  -0.0607    0.00391 -15.53   &lt;0.001 178.4 -0.0684 -0.05305

Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
Type:  response </code></pre>
</div>
</div>
<p>Para más detalles de que son estas probabilidades condicionales, y como se obvtienen se recomienda consultar <a href="https://www.andrewheiss.com/blog/2022/05/20/marginalia/">Heiss (2018)</a>.</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>